export const cards = [
  { id: "c-three", topic: "format", q: "Lance is three things at once. Name them.", a: "A file format, a table format and a lightweight catalog spec called Namespace." },
  { id: "c-rowgroups", topic: "format", q: "Why does Lance drop row groups?", a: "Small row groups create runt pages that read badly from object storage. Large ones force writers to buffer lots of memory. Without them, you don't lock in read patterns at write time." },
  { id: "c-backfill-lance", topic: "format", q: "What does Lance write when you backfill a new column?", a: "Only new data files for that column, added to each fragment. Existing data files stay untouched." },
  { id: "c-iceberg-nullable", topic: "iceberg", q: "Adding a nullable column in Iceberg costs what?", a: "Almost nothing. It's a metadata change. The expensive part is backfilling per-row values, which rewrites Parquet files because column chunks live inside row groups." },
  { id: "c-fragment", topic: "format", q: "What is a fragment?", a: "A horizontal slice of rows. It's a list in the manifest, not a file, and it holds one or more data files with the same row count." },
  { id: "c-versioning", topic: "format", q: "How does Lance version a table?", a: "Every commit writes a new immutable manifest. Time travel is built into the format." },
  { id: "c-deletes", topic: "format", q: "How are deletes handled in Lance?", a: "Deletion files mark rows as removed. Data files aren't rewritten, so indexes stay valid." },
  { id: "c-blobs", topic: "format", q: "How does Lance store blobs like video?", a: "As first-class columns stored out of line. Filters and vector search never touch the bytes, and readers can fetch a byte range. Blob v2 arrived with file format 2.2." },
  { id: "c-indexes", topic: "format", q: "Where do indexes live in Lance?", a: "In the format itself. Vector, full-text and scalar indexes are immutable files referenced by the manifest and versioned with the table." },
  { id: "c-encodings", topic: "format", q: "What are adaptive structural encodings?", a: "Lance picks a layout per column. Wide values like embeddings get a layout for predictable random access. Narrow values get a chunked, scan-friendly layout." },
  { id: "c-page", topic: "format", q: "Typical Lance page size?", a: "Around 8 MB per disk page." },
  { id: "c-pylance", topic: "format", q: "pylance vs lancedb?", a: "pylance is the format library for direct dataset control. lancedb is the embedded OSS lakehouse library with tables, a query builder and search on top." },
  { id: "c-geneva", topic: "format", q: "What is Geneva?", a: "LanceDB Enterprise's distributed feature engineering package. Versioned UDFs let you trace which code produced which feature column." },
  { id: "c-cache", topic: "format", q: "What problem does the training cache solve?", a: "Hundreds of GPUs reading object storage at once get throttled. The cache serves hot shards from NVMe near the compute." },
  { id: "c-chang", topic: "company", q: "Chang She in one breath?", a: "Early pandas core contributor, DataPad co-founder, Cloudera, VP of engineering at Tubi, former quant at AQR and Barclays. Co-founded LanceDB with Lei Xu." },
  { id: "c-funding", topic: "company", q: "LanceDB's funding?", a: "$8M seed in May 2024 led by CRV, $30M Series A in June 2025, about $41M total." },
  { id: "c-pb-users", topic: "proof", q: "Three petabyte-scale Lance users?", a: "Netflix's media data lake, Uber's multimodal AI data lake and Exa's exa-d pipelines." },
  { id: "c-stance", topic: "iceberg", q: "LanceDB's public stance on Iceberg?", a: "Coexistence. Iceberg for analytics interoperability, Lance for ML and AI where random access and cheap column updates matter." },
  { id: "c-sql", topic: "format", q: "How does SQL reach Lance tables?", a: "Through engines. The DuckDB Lance extension is the headline example." },
  { id: "c-hf", topic: "proof", q: "What did Lance ship with Hugging Face?", a: "Native read support on the Hub. A dataset ships as one artifact with blobs, embeddings and indexes." },
  { id: "c-governance", topic: "proof", q: "Lance's governance milestones?", a: "SDK 1.0 for Rust, Python and Java in December 2025, and a community governance model with contributors, maintainers and a PMC." },
  { id: "c-lancescope", topic: "lancescope", q: "Your LanceScope headline number?", a: "About 132 to 1. A table with 2.65 GB of video can be vector searched while reading none of the video." },
  { id: "c-cost", topic: "proof", q: "Cost benchmark to quote?", a: "100M vectors at roughly $779 a month." },
  { id: "c-reverie", topic: "company", q: "What is Reverie?", a: "LanceDB's summit for AI builders, announced in September 2026." },
  { id: "c-why-random", topic: "why-four", q: "Name three workloads that force random access.", a: "Training shuffles, vector search result fetches, and debugging or evaluation on specific sample IDs." },
  { id: "c-why-shuffle", topic: "why-four", q: "Why do training loaders read rows in random order?", a: "Models learn best from batches that are a random mix of the dataset. Reading in storage order biases batches toward one source or time window." },
  { id: "c-why-shards", topic: "why-four", q: "How do teams get shuffled reads on Parquet today, and what's the cost?", a: "Pre-shuffled shard copies like WebDataset or TFRecord. It's a second copy that goes stale when the source table changes." },
  { id: "c-embed-size", topic: "why-four", q: "Size of one 1,536-dimension float32 embedding?", a: "6,144 bytes. About 60 times a typical 100-byte analytics row, for one column. A billion of them is about 6 TB." },
  { id: "c-paths", topic: "why-four", q: "What breaks when blobs live in a bucket with paths in the table?", a: "Paths rot, compliance deletes mean chasing files, and reproducibility breaks because nothing guarantees the file is the one the model trained on." },
  { id: "c-blob-parquet", topic: "why-four", q: "What goes wrong putting 5 MB images inside Parquet?", a: "A 10,000-row row group means buffering 50 GB before a flush. Shrinking row groups splits narrow columns into slow runt pages." },
  { id: "c-facts-opinions", topic: "why-four", q: "Columns in analytics vs AI?", a: "Analytics columns are facts from the data model. AI columns are mostly model opinions: captions, embeddings, scores, labels. Every new model adds a column across all history." },
  { id: "c-backfill-math", topic: "why-four", q: "Backfill math for 1B images at 500 KB with a new 1,536-dim embedding?", a: "Table is about 500 TB. The column is about 6 TB. Lance writes 6 TB. A Parquet table where blobs share files could rewrite hundreds of terabytes." },
  { id: "c-caveat", topic: "why-four", q: "When does a team not need Lance?", a: "Small, text-only RAG. A few million documents run fine on Postgres with pgvector." },
  { id: "c-iceberg-origin", topic: "iceberg", q: "Where did Iceberg come from?", a: "Netflix, around 2017, built by Ryan Blue and Dan Weeks to fix Hive tables at petabyte scale. Apache top-level project since 2020." },
  { id: "c-hive", topic: "iceberg", q: "What was wrong with Hive tables?", a: "A table was whatever files sat in a directory. Planning meant listing millions of S3 objects, commits weren't atomic, and schema changes could corrupt data." },
  { id: "c-iceberg-tree", topic: "iceberg", q: "Iceberg's metadata tree, top to bottom?", a: "Catalog pointer, metadata.json (schema, partition spec, snapshots), manifest list, manifests with file stats, then Parquet data files." },
  { id: "c-tabular", topic: "iceberg", q: "What did Databricks pay for Tabular, and when?", a: "More than $1 billion, June 2024. Tabular had raised $37 million." },
  { id: "c-v3", topic: "iceberg", q: "What's new in Iceberg v3?", a: "Deletion vectors, row lineage, VARIANT, default column values, geospatial types, nanosecond timestamps and multi-argument transforms." },
  { id: "c-v3-ga", topic: "iceberg", q: "When did Iceberg v3 go GA on Snowflake?", a: "May 7, 2026. It's also on Databricks Runtime 18.0 and later." },
  { id: "c-v3-lance", topic: "iceberg", q: "What does Iceberg v3 change for Lance's pitch?", a: "Deletion vectors and default values close some gaps. Pitch what Iceberg can't copy without changing Parquet: random access into wide columns, out-of-line blobs, per-row backfills that write only the new column." },
  { id: "c-delta", topic: "analytics-formats", q: "Delta Lake in one line?", a: "Databricks' table format from 2019, Parquet plus a transaction log, now converging with Iceberg through UniForm." },
  { id: "c-hudi", topic: "analytics-formats", q: "Why does Hudi matter to your pitch?", a: "Uber created Hudi and still built its multimodal AI data lake on Lance." },
  { id: "c-parquet-origin", topic: "file-formats", q: "Where did Parquet come from?", a: "Twitter and Cloudera, around 2013, based on Google's Dremel paper." },
  { id: "c-vortex", topic: "file-formats", q: "What is Vortex and who backs it?", a: "A columnar file format from SpiralDB, now a Linux Foundation LF AI & Data project, supported by Microsoft, Snowflake and Palantir." },
  { id: "c-vortex-threat", topic: "file-formats", q: "Why is Vortex a threat to Lance?", a: "It targets fast random access and is heading into Iceberg. Microsoft showed 30% runtime reductions with Vortex inside Iceberg. That could weaken the random-access half of the pitch." },
  { id: "c-polaris", topic: "catalogs", q: "Apache Polaris status?", a: "Came from Snowflake, graduated to an Apache top-level project on February 19, 2026." },
  { id: "c-ducklake", topic: "catalogs", q: "What is DuckLake?", a: "The DuckDB team's lakehouse design with catalog metadata in a SQL database. v1.0 GA April 13, 2026." },
  { id: "c-s3v", topic: "vector", q: "S3 Vectors in one breath?", a: "GA December 2025. Up to 2 billion vectors per index, AWS claims up to 90% lower cost than vector databases, in 31 regions as of March 2026." },
  { id: "c-s3v-answer", topic: "vector", q: "Your answer to S3 Vectors?", a: "It stores vectors and metadata, not the images, features or training sets. Vector search is becoming a commodity, which is why selling the whole data layer is right." },
  { id: "c-turbopuffer", topic: "vector", q: "What is turbopuffer?", a: "Vector and full-text search built on object storage, close to LanceDB's retrieval design. Cursor is a publicly named customer." },
  { id: "c-mosaic", topic: "platforms", q: "Databricks' answer to training data?", a: "MosaicML Streaming, which came with the 2023 MosaicML acquisition." },
  { id: "c-vast", topic: "platforms", q: "Lance vs VAST in one line?", a: "An open format in any bucket and any cloud, versus a platform you buy." },
  { id: "c-threat-top", topic: "platforms", q: "Biggest threat to LanceDB, in your read?", a: "Platforms being 'good enough': Iceberg v3 in Databricks or Snowflake plus built-in vector search plus S3 Vectors." },
]
