import type { CompetitorEntry } from "./types";

/** Rivals the original competitor list left out, in the same shape. Threat is my
 *  read, on the same one-to-five scale. Researched September 2026. */
export const competitorsExtra: CompetitorEntry[] = [
  { id: "paimon", name: "Apache Paimon", group: "table-format", threat: 3,
    sourceIds: ["paimon-formats", "paimon-blob", "doris-paimon-2"],
    origin: "Grew out of the Apache Flink community and became an Apache project.",
    whatItIs: "An LSM-based streaming lakehouse table format with primary-key and append tables, now adding blobs, vector types and a global vector index.",
    whyItMatters: "It is the table format converging fastest on Lance's feature list: column evolution without rewrites, a dedicated blob file type, a vector index, and Lance as a supported data file format. Its own docs recommend Lance files for ML workloads. Apache Doris 4.2, due at the end of September 2026, queries Paimon, Iceberg and Lance as a multimodal lakehouse.",
    lanceAngle: "Paimon recommending Lance files for ML is an endorsement worth quoting. The difference: in Lance, blobs, column evolution and indexes are native and on by default. In Paimon they are newer opt-in modes on a Flink-first streaming format." },

  { id: "pinecone", name: "Pinecone", group: "vector", threat: 2,
    sourceIds: ["pinecone-ceo", "pinecone-one-year", "calcalist-pinecone", "pinecone-nexus"],
    origin: "Founded in 2019 by Edo Liberty, who had run Amazon's AI lab.",
    whatItIs: "The best-known managed vector database, now repositioning as a 'knowledge' company with Pinecone Nexus, which went GA in August 2026.",
    whyItMatters: "It defined the vector database category, and LanceDB started in that category. Calcalist reported in August 2025 that Pinecone explored a sale after losing Notion as a customer. Notion reportedly moved to turbopuffer. It has $138M raised, with the last round in 2023.",
    lanceAngle: "Pinecone is a separate retrieval silo: you copy embeddings in, and the source data lives somewhere else. Its own moves toward BYOC and 'knowledge' show that buyers want the data in their own account. Lance has worked that way from the start." },

  { id: "milvus", name: "Milvus and Zilliz", group: "vector", threat: 4,
    sourceIds: ["milvus-3", "zilliz-lakebase", "bf-lakebase", "tracxn-zilliz"],
    origin: "Milvus started at Zilliz and is now a graduated LF AI & Data project.",
    whatItIs: "The most-starred open-source vector database, now pitched by Zilliz as a 'Vector Lakebase' for serving, discovery and training-data pipelines.",
    whyItMatters: "This is the vector database moving directly onto LanceDB's ground. Zilliz launched Vector Lakebase in public preview in June 2026. Milvus 3.0 (July 2026) can index Lance, Iceberg, Parquet and Vortex data in place, read-only, through External Collections, and uses Vortex as its own default storage format.",
    lanceAngle: "Milvus reading Lance shows Lance has become a format the lake is expected to speak. But Milvus reads it read-only and wants its own storage for writes and serving. LanceDB is the native engine for the format: writes, versions, schema evolution, blobs and indexes all live in one table, with no second system to run." },

  { id: "qdrant", name: "Qdrant", group: "vector", threat: 2,
    sourceIds: ["qdrant-series-b", "qdrant-1-16"],
    origin: "Founded in Berlin.",
    whatItIs: "A Rust vector database with strong filtered HNSW search, running on RAM or local disk, with cloud, hybrid, private and edge deployments.",
    whyItMatters: "It has fresh 2026 funding and a reputation for fast, predictable filtered search. It is often the pick when latency on a warm index is the main requirement.",
    lanceAngle: "Qdrant keeps vectors and payloads on node-local disk or RAM, which gets expensive at hundreds of terabytes, and it has no dataset versioning. Compare total cost and the number of copies of the data, not p50 latency on a warm benchmark." },

  { id: "weaviate", name: "Weaviate", group: "vector", threat: 2,
    sourceIds: ["weaviate-series-b", "weaviate-1-38", "weaviate-pricing"],
    origin: "Founded in 2019 in Amsterdam.",
    whatItIs: "A Go vector database with hybrid search, native multi-tenancy, built-in vectorizers and a disk-based HFresh index, which went GA in v1.38.",
    whyItMatters: "It is moving up into agent products: Query Agent, Engram memory (GA in June 2026) and an MCP server. It prices by stored vector dimensions.",
    lanceAngle: "A good RAG backend, but not a place for training data, blobs or versioned features. Pricing by vector dimensions grows with embedding size, while Lance on object storage grows with bytes at storage cost." },

  { id: "chroma", name: "Chroma", group: "vector", threat: 2,
    sourceIds: ["chroma-serverless", "chroma-pricing"],
    origin: "Founded in San Francisco as an open-source embedding store for AI apps.",
    whatItIs: "An open-source, embeddable vector store and a hosted Chroma Cloud, built in Rust on object storage, for many small collections.",
    whyItMatters: "It is the default local vector store in many tutorials, and its cloud design (WAL, compactors, query nodes caching from S3) is close in shape to LanceDB's and turbopuffer's.",
    lanceAngle: "It has a similar deployment shape but a different scope. Chroma is a retrieval index for AI apps. Lance is a columnar format and engine for all the AI data, with blobs, features, embeddings and indexes in one versioned table readable by Spark, Ray and DuckDB." },

  { id: "search-incumbents", name: "Elastic, OpenSearch, MongoDB, Vespa", group: "vector", threat: 2,
    sourceIds: ["elastic-diskbbq", "mongodb-voyage", "vespa-perplexity", "google-agent-retrieval"],
    origin: "Established search and database vendors that added vector search to systems customers already run.",
    whatItIs: "Elasticsearch (DiskBBQ quantized disk index), OpenSearch (GPU index builds, S3 Vectors as an engine), MongoDB Atlas Vector Search (with Voyage AI embeddings) and Vespa (tensor ranking at web scale; Perplexity is a customer).",
    whyItMatters: "They win by default wherever the customer already runs them. Vector search is a feature of their product, not the whole product.",
    lanceAngle: "Each is a search or operational cluster on local disk, not a store for training data or blobs. Lance sits beside them as the source-of-truth table that search indexes are built from, and that training reads." },

  { id: "spiral", name: "Spiral", group: "multimodal", threat: 4,
    sourceIds: ["spiral-site", "spiral-announce", "gunder-spiral", "lf-vortex"],
    origin: "Founded by the team that created the Vortex file format.",
    whatItIs: "A multimodal data platform built on the Vortex format, pitched at ML and robotics teams: object-storage-native, with branches and tags and GPU data loading.",
    whyItMatters: "The closest architectural rival to LanceDB: a new open format with claimed random-access gains over Parquet, and a commercial platform on top. It names Chef Robotics, Skild AI and Figure AI as customers. It is in early access.",
    lanceAngle: "Both beat Parquet on random access. Lance ships indexes, blob handling, column evolution and a production search engine today, plus the Hugging Face, Ray, Daft and Spark integrations. Spiral is still onboarding a few teams at a time." },

  { id: "deeplake", name: "Activeloop Deep Lake", group: "multimodal", threat: 3,
    sourceIds: ["deeplake-gh", "deeplake-pg", "activeloop-series-a", "gradientflow-mmlh"],
    origin: "Activeloop came through Y Combinator (S18) with a format for deep learning datasets.",
    whatItIs: "A tensor storage format on object storage with versioning, streaming PyTorch and TensorFlow loaders, and a Postgres interface (Deep Lake PG, December 2025).",
    whyItMatters: "It was early to the idea of versioned multimodal datasets with training loaders, which is Lance's ground. It has repositioned several times: data lake for deep learning, then vector store, then 'GPU database for agents', and now continual learning infrastructure.",
    lanceAngle: "Lance is an open table format many engines read natively, with random access, vector and full-text indexes, and zero-copy column evolution in the format. It also has petabyte-scale references. Deep Lake keeps changing what it is." },

  { id: "pixeltable", name: "Pixeltable", group: "multimodal", threat: 2,
    sourceIds: ["pixeltable-seed", "pixeltable-pypi", "gradientflow-mmlh"],
    origin: "Founded by Marcel Kornacker, creator of Apache Impala and co-creator of Parquet.",
    whatItIs: "A Python library where tables hold image, video, audio and document columns, and computed columns (model calls, UDFs) update incrementally.",
    whyItMatters: "It is small, but its founders carry real weight in data formats. The declarative, incremental computed-column model is the same idea as Geneva, aimed at app builders.",
    lanceAngle: "Pixeltable targets a single application backend; Gradient Flow describes it as built on Postgres and pgvector. Geneva runs the same kind of incremental backfill distributed on Ray, over an open columnar format built for petabytes." },

  { id: "aperturedb", name: "ApertureData (ApertureDB)", group: "multimodal", threat: 2,
    sourceIds: ["aperture-seed", "aperture-docs"],
    origin: "Founded in 2018 by two researchers from Intel Labs.",
    whatItIs: "A 'graph-vector database' that stores images and video natively, keeps annotations in an in-memory property graph, and runs FAISS-based vector search.",
    whyItMatters: "It targets visual AI with heavy annotations, such as retail and manufacturing, where relationships between objects matter.",
    lanceAngle: "It is a proprietary database server, not an open format on object storage. Lance models relationships as columns and joins through engines. It is the better fit wherever scale, open access and training reads matter more than graph traversal." },

  { id: "daft", name: "Daft (Eventual)", group: "engine", threat: 1,
    sourceIds: ["eventual-30m", "daft-lance", "daft-roadmap"],
    origin: "Eventual was founded by two engineers from Lyft's self-driving unit, Level 5.",
    whatItIs: "A Rust-core, Python-native distributed DataFrame engine with native multimodal types, running locally or on Ray.",
    whyItMatters: "Mostly a partner. Daft reads and writes Lance natively, including version reads, vector search and merge_columns. Eventual's website now pitches scenario mining for robot fleet data, which could overlap with LanceDB in physical AI accounts.",
    lanceAngle: "Daft is compute, not storage. It is often the engine writing to Lance, so it is a partner. Watch Eventual's robotics curation product." },

  { id: "ray", name: "Ray and Anyscale", group: "engine", threat: 1,
    sourceIds: ["nscale-anyscale", "bloomberg-anyscale", "ray-read-lance", "lance-ray-gh"],
    origin: "Ray came out of UC Berkeley's RISELab. Anyscale was founded by its creators.",
    whatItIs: "The distributed runtime most AI data pipelines run on. Ray Data has a native read_lance, and lance-ray adds distributed writes.",
    whyItMatters: "Geneva runs on Ray. Nscale is a GPU cloud, so owning Anyscale could bundle the managed product with Nscale's compute. Ray itself stays community-governed under the PyTorch Foundation.",
    lanceAngle: "A partner. Geneva depends on open-source Ray, not on Anyscale's product. If asked about the Nscale deal, that is the answer." },

  { id: "huggingface", name: "Hugging Face (and Nvidia)", group: "engine", threat: 1,
    sourceIds: ["nvidia-hf", "hf-lance-docs", "lancedb-hf-blog", "hf-xet"],
    origin: "Started as a chatbot company and became the main hub for sharing open models and datasets.",
    whatItIs: "The default place AI datasets and models are shared, with Xet deduplicated storage. The Hub documents Lance as a supported format: scan, filter, take blobs and vector search on hf:// paths.",
    whyItMatters: "Distribution. A Lance dataset on the Hub carries its blobs, embeddings and indexes as one artifact. Nvidia ownership gives the Hub more reach and puts it in the GPU vendor's orbit.",
    lanceAngle: "A partner, not a rival. The Hub distributes and Lance makes the data queryable in place. A larger Nvidia-backed Hub means more reach for Lance datasets." },

  { id: "hyperscaler-lakehouses", name: "Google BigQuery and Microsoft Fabric", group: "platform", threat: 3,
    sourceIds: ["google-lakehouse-2026", "google-agent-retrieval", "fabric-multimodal"],
    origin: "The analytics platforms of the other two major clouds.",
    whatItIs: "BigQuery ObjectRef columns (GA April 2026) point at Cloud Storage objects from inside tables, including managed Iceberg, with multimodal embeddings and vector search. Fabric AI Functions accept image and PDF paths (preview), with Azure AI Search as the vector store.",
    whyItMatters: "Every major cloud now says 'multimodal lakehouse'. They adopt the vocabulary LanceDB helped popularize, and they win on default status inside their own clouds.",
    lanceAngle: "Both model media as pointers to objects plus a separate vector service. Lance stores the bytes, embeddings and indexes in one versioned table with fast random access, and it runs on every cloud's object storage." },
];
