export const competitors = [
  { id: "iceberg", name: "Apache Iceberg", group: "table-format", threat: 5,
    sourceIds: ["tt-tabular", "db-tabular", "atlan-v3", "ryft-v3", "iceberg-intro-2026", "register-lance"],
    origin: "Built at Netflix around 2017 by Ryan Blue and Dan Weeks. Donated to Apache and a top-level project since 2020.",
    whatItIs: "The default open table format for analytics. A metadata tree over Parquet files that brings atomic commits, snapshots, time travel, hidden partitioning and safe schema evolution to object storage.",
    whyItMatters: "Netflix built it because Hive tables broke at petabyte scale: Hive treated a table as whatever files were in a directory, so planning meant listing millions of S3 objects, commits weren't atomic, and schema changes could corrupt data. Iceberg won the format war once Snowflake and Databricks both went all in. Databricks confirmed it paid more than $1 billion for Tabular, the Iceberg creators' company, in June 2024. Tabular had raised $37 million. Snowflake open-sourced its Polaris catalog, and AWS launched S3 Tables as managed Iceberg. Iceberg v3 went GA on Snowflake on May 7, 2026 and on Databricks Runtime 18.0+, adding deletion vectors, row lineage, VARIANT, default column values, geospatial types, nanosecond timestamps and multi-argument transforms. Engine support is uneven. As of late 2025 Athena did not support v3. v4 proposals include single-file commits.",
    lanceAngle: "Coexist, and differentiate below the table layer. Iceberg is absorbing good ideas (deletion vectors, default values), so pitch what it can't copy without changing Parquet: random access into wide columns, out-of-line blobs, and per-row backfills that write only the new column. Default values don't help when every row needs its own 6 KB vector." },
  { id: "delta", name: "Delta Lake", group: "table-format", threat: 3,
    sourceIds: ["bf-tabular", "db-v3", "db-tabular"],
    origin: "Databricks' table format, open-sourced in 2019 and now under the Linux Foundation.",
    whatItIs: "Parquet files plus a transaction log. Same core idea as Iceberg, deepest inside Spark and Databricks.",
    whyItMatters: "Databricks built Delta Lake UniForm in 2023 so a Delta table can also be read as Iceberg or Hudi. Its strategy now is convergence: Databricks says Iceberg v3 deletion vectors share the same binary encoding across formats and v3 row lineage is compatible with Delta's row tracking.",
    lanceAngle: "Treat Delta and Iceberg as one analytics camp. The Lance argument is the same for both." },
  { id: "hudi", name: "Apache Hudi", group: "table-format", threat: 1,
    sourceIds: ["dq-lance"],
    origin: "Created at Uber in 2016. Onehouse, founded by Hudi's creator, sells it commercially.",
    whatItIs: "A table format tuned for frequent upserts, deletes and streaming ingestion.",
    whyItMatters: "Rarely the competitor in an AI deal. Its value to you is the Uber story.",
    lanceAngle: "Uber created Hudi and still built its distributed multimodal AI data lake on Lance. The company that wrote an analytics table format picked a different format when the data went multimodal." },
  { id: "parquet", name: "Apache Parquet", group: "file-format", threat: 3,
    sourceIds: ["dq-lance", "lance-paper"],
    origin: "Built by Twitter and Cloudera around 2013, based on Google's Dremel paper.",
    whatItIs: "The columnar file format under Iceberg, Delta and Hudi. Rows grouped into row groups, column chunks inside each, located by a footer.",
    whyItMatters: "Excellent at sequential scans, which is why analytics runs on it. The row group design forces a tradeoff between runt pages and writer memory, and makes random access and per-row backfills expensive.",
    lanceAngle: "Chang knows Parquet's history from Cloudera. Don't explain Parquet to him. Name its limits precisely: row groups, footer-located chunks, page-granularity reads for single values." },
  { id: "vortex", name: "Vortex", group: "file-format", threat: 4,
    sourceIds: ["lf-vortex", "vortex-gh", "duckdb-vortex"],
    origin: "Created by SpiralDB. Donated to the Linux Foundation's LF AI & Data as an incubation project in August 2025, with support from Microsoft, Snowflake and Palantir.",
    whatItIs: "A next-generation columnar file format with pluggable encodings and cascading compression that can run filters on compressed data.",
    whyItMatters: "The project claims 100x faster random access than modern Parquet, 10 to 20x faster scans and 5x faster writes at similar compression. These are vendor numbers. Microsoft showed 30% runtime reductions running Spark workloads with Vortex inside Iceberg, and Iceberg integration is listed as coming soon. DuckDB shipped a Vortex extension in January 2026.",
    lanceAngle: "The sleeper threat. If Iceberg plus Vortex delivers fast random access, the random-access half of Lance's pitch weakens while the incumbent keeps its ecosystem. Lance still has out-of-line blobs, per-column data files for cheap backfills, and indexes versioned with the table. Position Lance as a complete AI table, not only a faster file format. Asking Chang how he thinks about Vortex shows real homework." },
  { id: "nimble", name: "Nimble", group: "file-format", threat: 1,
    sourceIds: ["vortex-gh"],
    origin: "Meta's file format.",
    whatItIs: "A columnar format built for very wide ML feature tables.",
    whyItMatters: "Mostly internal to Meta's stack, but it appears in format benchmarks, including Vortex's Velox prototype comparing Vortex, Parquet and Nimble.",
    lanceAngle: "Evidence that big AI shops outgrew Parquet for ML data. Supports the category, not a direct rival." },
  { id: "catalogs", name: "Polaris, Unity, Gravitino", group: "catalog", threat: 2,
    sourceIds: ["datalake-2026"],
    origin: "Polaris came from Snowflake and graduated to an Apache top-level project on February 19, 2026. Unity Catalog is Databricks' governance layer. Gravitino is an Apache project for federated metadata across formats.",
    whatItIs: "The layer that decides which tables engines can see and who can access them.",
    whyItMatters: "Whoever owns the catalog shapes which formats feel first-class.",
    lanceAngle: "Lance's Namespace spec is a bet on showing up inside these catalogs instead of competing with them. 'Your catalog can see Lance tables next to your Iceberg tables.'" },
  { id: "ducklake", name: "DuckLake", group: "catalog", threat: 1,
    sourceIds: ["datalake-2026"],
    origin: "From the DuckDB team. v1.0 GA on April 13, 2026.",
    whatItIs: "A lakehouse design that keeps catalog metadata in a SQL database (SQLite, PostgreSQL or DuckDB) instead of metadata files.",
    whyItMatters: "Not an AI competitor. It shows a small, credible team can challenge Iceberg's design.",
    lanceAngle: "Useful support for 'the analytics formats aren't the last word.'" },
  { id: "vector-dbs", name: "Pinecone, Milvus, Qdrant, Weaviate, Chroma", group: "vector", threat: 2,
    sourceIds: ["tracxn"],
    origin: "Dedicated vector databases. Milvus is sold commercially by Zilliz.",
    whatItIs: "Systems built for fast similarity search over embeddings.",
    whyItMatters: "The category LanceDB started in. Tracxn still lists Pinecone and Qdrant among LanceDB's top competitors.",
    lanceAngle: "Vector databases hold vectors. The images, features and training sets live elsewhere. Lance keeps vectors next to the source data in one versioned table." },
  { id: "pgvector", name: "pgvector", group: "vector", threat: 2,
    sourceIds: [],
    origin: "A Postgres extension.",
    whatItIs: "Vector search inside Postgres.",
    whyItMatters: "Wins most small RAG projects by default because teams already run Postgres.",
    lanceAngle: "Concede it. Small text-only RAG is fine on pgvector. Lance's customers are the ones who outgrow it with multimodal data and training." },
  { id: "turbopuffer", name: "turbopuffer", group: "vector", threat: 3,
    sourceIds: [],
    origin: "A search engine built on object storage.",
    whatItIs: "Vector and full-text search built directly on object storage, a design close to LanceDB's own retrieval layer.",
    whyItMatters: "A strong, well-regarded retrieval competitor. Cursor is one of its publicly named customers.",
    lanceAngle: "Competes on retrieval, not on training data or feature engineering. The lakehouse positioning moves the fight to ground turbopuffer doesn't cover." },
  { id: "s3-vectors", name: "Amazon S3 Vectors", group: "vector", threat: 4,
    sourceIds: ["aws-s3v-ga", "aws-s3v-regions"],
    origin: "AWS. Previewed July 2025, GA December 2, 2025.",
    whatItIs: "Native vector storage and similarity search inside S3.",
    whyItMatters: "AWS claims up to 90% lower cost to upload, store and query vectors than dedicated vector databases. Up to 2 billion vectors per index and 10,000 indexes per vector bucket. Frequent queries around 100 ms. Available in 31 regions as of March 2026. Integrates with Bedrock Knowledge Bases and OpenSearch.",
    lanceAngle: "Squeezes every 'cheap vectors on object storage' pitch, including LanceDB's. The answer: S3 Vectors stores vectors plus metadata, not the images, captions, ten generations of features or the training set. Vector search is becoming a commodity feature, which is why selling the whole data layer is the right move." },
  { id: "databricks-snowflake", name: "Databricks and Snowflake", group: "platform", threat: 5,
    sourceIds: ["db-tabular", "atlan-v3"],
    origin: "The two dominant data platforms.",
    whatItIs: "Full platforms with storage, compute, governance and built-in vector search, both now centered on Iceberg-compatible tables.",
    whyItMatters: "They want to own AI data too. Databricks bought MosaicML in 2023, which brought MosaicML Streaming for feeding training data from object storage.",
    lanceAngle: "The 'good enough' threat. Answer with portability and the four needs: one open table for curation, features, retrieval and training that runs next to whatever platform the customer already has." },
  { id: "vast", name: "VAST Data", group: "platform", threat: 3,
    sourceIds: ["tracxn"],
    origin: "Storage company that expanded into a database layer for AI.",
    whatItIs: "Storage plus a database sold as one system for AI data.",
    whyItMatters: "Tracxn lists VAST among LanceDB's top competitors, and it pitches unified AI data infrastructure.",
    lanceAngle: "An open format in any bucket and any cloud, versus a platform you buy. Lead with the neocloud story: keep the source of truth in object storage and put caches next to whichever GPUs you rent." },
  { id: "training-formats", name: "WebDataset, TFRecord, MosaicML Streaming", group: "training-data", threat: 2,
    sourceIds: [],
    origin: "Open formats and libraries for training data. MosaicML Streaming came to Databricks with the MosaicML acquisition.",
    whatItIs: "Pre-shuffled shard files that stream training data from object storage.",
    whyItMatters: "The DIY way teams get random-order training reads today.",
    lanceAngle: "Each is a second copy of the data that goes stale when the source table changes. Lance serves shuffled reads from the source table itself, with the training cache for GPU throughput." },
]

export const threatRanking = {
  caption: "My read, not industry consensus. Test it against what Chang says.",
  items: [
    { id: "good-enough", label: "Platforms being 'good enough'", score: 5, text: "Iceberg v3 inside Databricks or Snowflake, plus built-in vector search, plus S3 Vectors, might convince buyers they don't need another format." },
    { id: "vortex-iceberg", label: "Vortex inside Iceberg", score: 4, text: "Attacks the random-access argument while keeping the incumbent's ecosystem." },
    { id: "object-vector", label: "Object-storage vector search", score: 3, text: "turbopuffer and S3 Vectors compress the retrieval market." },
    { id: "vector-dbs", label: "Dedicated vector databases", score: 2, text: "LanceDB is already positioned above them." },
  ],
  throughLine: "Every competitor solves one or two of the four needs well. LanceDB's bet is that one versioned table doing all four beats stitching together the best tool for each. Your job as a technical marketer would be to make that bet visible with data.",
}
