import type { CompetitorDetail } from "./types";

/** Vector and retrieval systems. Researched September 2026. */
export const vectorDetails: CompetitorDetail[] = [
  {
    id: "vector-dbs", asOf: "2026-09",
    howItWorks: "Dedicated vector databases hold embeddings plus metadata and serve approximate nearest-neighbour search. They split into two designs. Pinecone, Chroma and turbopuffer keep data on object storage and cache hot data in memory and SSD. Qdrant and Weaviate keep it in RAM or on local disk. Milvus is moving toward the lake, with tiered storage and read-only indexes over Lance, Iceberg and Parquet.",
    status: "The category is converging on LanceDB's thesis from several directions. Milvus 3.0 reads Lance files in place, and Zilliz now sells a 'Vector Lakebase' aimed at training pipelines. Pinecone repositioned as a 'knowledge' company. Qdrant raised $50M in March 2026. Weaviate and Chroma are moving into agent memory. Each has its own profile.",
    strengths: [
      "Fast, mature approximate search with rich filtering.",
      "Managed services with low operating effort.",
      "Established brands in RAG.",
    ],
    weaknesses: [
      "They hold vectors and metadata, not the source images, video, features or training sets.",
      "Their own storage formats aren't readable by Spark, DuckDB or PyTorch.",
      "No dataset versioning for ML reproducibility.",
      "Every new embedding model means re-exporting and re-indexing into a second system.",
    ],
    whereItWins: "A retrieval API for an application whose source data already lives, and stays, elsewhere.",
    whereLanceWins: "One versioned table for source data, features, embeddings and indexes, serving retrieval, analytics and training from one copy on object storage.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Why isn't LanceDB just another vector database?",
      a: "Because vector search is one workload on the table, not the product. Every vector database is fast at lookups. None of them holds the images, the ten generations of features and the training set, versioned together. That's the gap the multimodal lakehouse fills.",
    },
    sourceIds: ["milvus-3", "zilliz-lakebase", "pinecone-nexus", "qdrant-series-b", "tracxn"],
  },
  {
    id: "pinecone", asOf: "2026-09",
    company: "Founded in 2019 by Edo Liberty. Ash Ashutosh, who founded Actifio, became CEO in September 2025. In August 2026 Pinecone said Liberty is stepping back from day-to-day work and stays on the board. $138M raised in total; the last round was a $100M Series B at a $750M valuation in April 2023, led by a16z.",
    howItWorks: "Serverless, with storage separated from compute. Writes go to a log and an in-memory memtable, then into immutable 'slabs' on object storage that compaction merges and indexes. Stateless query executors cache slabs in memory and on SSD. It supports dense, sparse and full-text indexes with metadata filtering, plus dedicated read nodes for heavy load.",
    status: "Pinecone Nexus, a 'knowledge engine' that compiles enterprise data into governed context for agents, entered preview on July 1, 2026 and went GA on August 6. It runs in the customer's own AWS, GCP or Azure account. Full-text search went GA on September 9, 2026. Calcalist reported in August 2025 that Pinecone explored a sale after losing Notion; no sale has happened.",
    pricing: "Usage-based with plan minimums: Standard $50 a month, Enterprise $500 a month, storage $0.33 per GB-month, plus per-million read and write units. BYOC is Enterprise only. These are vendor list prices.",
    customers: "Adobe, Cisco, Microsoft, Workday, Vanguard, HubSpot, Gong, Duolingo, Zapier, OpenAI and Cohere, among others (Pinecone's customer page). Notion was a customer and left.",
    strengths: [
      "The best-known brand in the category, with a large installed base.",
      "Fully managed and serverless, with no index tuning.",
      "Dense, sparse and full-text search in one service, plus BYOC.",
      "Moving up the stack into governed agent knowledge.",
    ],
    weaknesses: [
      "Closed and proprietary, with no open file format.",
      "Holds vectors and metadata, not source data, blobs, features or training sets.",
      "No embedded mode and no dataset versioning.",
      "Read and write unit pricing gets expensive for bulk or training-style access.",
      "Strategic uncertainty: a reported sale exploration, a founder stepping back and a product pivot.",
    ],
    whereItWins: "A team that wants a turnkey managed vector and hybrid search API for RAG, is fine with proprietary SaaS, and doesn't need the data in its own lake.",
    whereLanceWins: "Multimodal data and blobs, training and feature pipelines, versioned datasets, embedded use, and data kept in open files on the customer's own storage.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Pinecone is the default vector database and just shipped full-text. Why LanceDB?",
      a: "Pinecone is a strong retrieval service, but it's a separate silo: you copy embeddings in and the source data lives elsewhere. With Lance the source data, blobs, features, embeddings and indexes are one versioned table in an open format on your own storage. Pinecone's own move to BYOC shows buyers want the data in their account, and Lance has worked that way from the start.",
    },
    vendorClaims: [
      "10,000+ customers and 1M+ developers.",
      "Serverless net retention above 130% and a 96% serverless gross margin.",
      "Nexus: 74% lower cost per task and up to 30 times faster.",
    ],
    uncertain: ["Whether the reported sale process is still active.", "Current headcount and revenue."],
    sourceIds: ["pinecone-ceo", "pinecone-one-year", "calcalist-pinecone", "pinecone-nexus", "pinecone-pricing", "pinecone-arch"],
  },
  {
    id: "milvus", asOf: "2026-09",
    company: "Zilliz, led by founder and CEO Charles Xie, sells Milvus as Zilliz Cloud. Tracxn lists about $113M raised over four rounds; the last one found is a $60M Series B in August 2022. Milvus is a graduated LF AI & Data project under Apache 2.0.",
    howItWorks: "A distributed, cloud-native design that separates storage from compute and persists data to object storage. Milvus 2.6 (June 2025) added hot and cold tiered storage, RaBitQ quantization and a write-ahead log on object storage. Milvus 3.0 added 'Loon' storage with Vortex as the default format, and read-only, zero-copy External Collections over Lance, Iceberg, Parquet and Vortex. It also added server-side aggregation, multi-vector support, snapshots, a Spark connector and online schema evolution. Index types include HNSW, IVF, DiskANN, GPU indexes and sparse indexes.",
    status: "Milvus 3.0 was announced on July 27, 2026, and 3.0.2 shipped on September 20. Zilliz Vector Lakebase entered public preview on June 10, 2026, cloud-only, on AWS, GCP and Azure. It combines several serving tiers, on-demand search and external data lake search, and is pitched as one foundation for serving, discovery and multi-petabyte training-data pipelines.",
    pricing: "Zilliz Cloud storage is $0.04 per GB-month from January 2026, down from $0.30, and compute was cut 25% in October 2025. Milvus itself is free.",
    customers: "Zillow, OpenEvidence, Exa, Filevine, MiniMax, Salesforce and Read AI (Zilliz Vector Lakebase launch release). Exa also appears on LanceDB's own list.",
    strengths: [
      "The most-starred open-source vector database, with about 46,000 GitHub stars.",
      "The widest choice of index types, including GPU and DiskANN, and proven billion-scale deployments.",
      "Apache 2.0, with a managed cloud on three clouds plus BYOC.",
      "3.0 indexes Lance, Iceberg and Parquet in place, which blunts the 'data stays in the lake' argument.",
    ],
    weaknesses: [
      "Self-hosting a distributed Milvus cluster on Kubernetes is heavy to operate.",
      "External Collections are read-only; the primary store is still Milvus's own format.",
      "Vector Lakebase is cloud-only and in preview.",
      "Its lakehouse story is months old; Lance's is years old.",
    ],
    whereItWins: "Large vector search clusters that need high query throughput, GPU indexing and many index choices, run by a team comfortable with a distributed database.",
    whereLanceWins: "One open, versioned table for multimodal data, features and embeddings, used for both training and serving; embedded use with no cluster; random access into blobs. Milvus consumes the Lance format; LanceDB is its native engine.",
    fourNeeds: { scans: "partial", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Milvus 3.0 can search your Lance files in place. Why do you need LanceDB?",
      a: "It shows Lance has become a format the lake is expected to speak. But Milvus reads it read-only and keeps its own storage for writes and serving. LanceDB is where writes, versions, schema evolution, blobs and indexes all live in the same table, with no second system to operate.",
    },
    vendorClaims: [
      "10,000+ enterprises and AI teams.",
      "Loon cuts I/O per point read about 135 times.",
      "On-demand search about $318 a month against $4,937 for a 'comparable serverless' option (Zilliz internal benchmark).",
    ],
    uncertain: ["Funding after 2022, headcount and revenue."],
    sourceIds: ["milvus-3", "zilliz-lakebase", "bf-lakebase", "tracxn-zilliz"],
  },
  {
    id: "qdrant", asOf: "2026-09",
    company: "Berlin-founded, led by co-founder and CEO Andre Zayarni. A $50M Series B led by AVP closed on March 12, 2026, with Bosch Ventures, Unusual Ventures and Spark Capital. About $88M raised in total.",
    howItWorks: "Written in Rust. An HNSW index with vectors in RAM or memory-mapped on disk, filtering built into the graph traversal, dense, sparse and multi-vector search, and hybrid queries composed at query time. Quantization options go down to 4-bit. Tiered multitenancy moves large tenants onto dedicated shards. Data lives on node-local disk, not object storage.",
    status: "v1.19 shipped in August 2026. In April 2026 Qdrant Cloud added GPU-accelerated indexing, multi-AZ clusters and audit logs. Qdrant Edge offers on-device retrieval with cloud sync.",
    pricing: "Managed cloud is billed hourly for vCPU, RAM and disk, with a small free tier. Hybrid and private cloud are sold through sales.",
    customers: "Canva, Bazaarvoice, HubSpot, Roche, Bosch, OpenTable (Qdrant's Series B post).",
    strengths: [
      "Fast, predictable latency from Rust, and strong filtered search.",
      "Popular open source, with about 35,000 GitHub stars.",
      "Flexible deployment, from embedded to edge.",
      "Aggressive quantization and GPU indexing.",
    ],
    weaknesses: [
      "RAM and local-disk architecture gets expensive at 100 TB to petabyte scale.",
      "Vectors and payload only, with no versioning.",
      "A proprietary storage format.",
      "Clusters need capacity planning.",
    ],
    whereItWins: "Low-latency, filter-heavy online search at moderate scale, and edge or on-device retrieval.",
    whereLanceWins: "Large multimodal data on object storage, training and feature engineering in the same table as retrieval, and versioned datasets.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Qdrant is faster on filtered search benchmarks.",
      a: "For a hot, RAM-sized index on dedicated nodes, it can be. Lance targets a different cost and scale point: data on object storage, indexes cached, and the same table serving ML pipelines. Compare total cost and the number of copies, not p50 on a warm benchmark.",
    },
    vendorClaims: ["250M+ downloads.", "'8x compression without the recall tax' from TurboQuant."],
    sourceIds: ["qdrant-series-b", "qdrant-1-16"],
  },
  {
    id: "weaviate", asOf: "2026-09",
    company: "Founded in 2019 in Amsterdam by Bob van Luijt (CEO) and Etienne Dilocker (CTO). Its $50M Series B, led by Index Ventures, was in April 2023. RICOH's innovation fund invested an undisclosed amount in 2026. Tracxn estimates about $68M in total.",
    howItWorks: "Written in Go. Index types include in-memory HNSW, flat, dynamic, and HFresh, a disk-based index based on SPFresh that keeps a small in-memory graph over centroids. It offers hybrid BM25 plus vector search, native multi-tenancy and built-in embedding modules. Storage is on node-local disk.",
    status: "HFresh and an MCP server went GA in v1.38 (June 2026). v1.39 (August) made MMR diversity GA, and v1.40 is in release candidate. Engram, a managed memory service for agents, went GA on June 24, 2026.",
    pricing: "Billed on stored vector dimensions plus storage and backups. Flex starts at $45 a month; Premium at $400 a month prepaid. These are vendor list prices.",
    customers: "Akamai, Booking, Bosch, Cisco, Intuit, NetApp, Scribd and Thales (logos on Weaviate's homepage).",
    strengths: [
      "Mature hybrid search and multi-tenancy, with good developer experience.",
      "Agent products: Query Agent, Engram memory, MCP server.",
      "Flexible deployment, including BYOC.",
      "The HFresh disk index lowers memory cost.",
    ],
    weaknesses: [
      "Local-disk architecture, and pricing that grows with embedding dimensions.",
      "Not a training or analytics store.",
      "A smaller open-source footprint, about 17,000 GitHub stars.",
      "No disclosed priced round since 2023.",
    ],
    whereItWins: "Multi-tenant SaaS apps that want hybrid search and built-in vectorization, and teams that want agent features out of the box.",
    whereLanceWins: "Multimodal lakehouse workloads, cheap storage at huge scale, and ML training and feature pipelines on the same data.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Weaviate has built-in vectorizers and agents. Isn't that easier?",
      a: "For a RAG app it can be, and LanceDB also has embedding functions and hybrid search. The difference is where the data lives. Lance keeps raw assets, features and embeddings in one open, versioned table you own, which matters once the same data feeds training and evaluation.",
    },
    vendorClaims: ["Download figures conflict: '20M+ open source downloads' on the homepage against '150 million times monthly' in a press release."],
    sourceIds: ["weaviate-series-b", "weaviate-1-38", "weaviate-pricing"],
  },
  {
    id: "chroma", asOf: "2026-09",
    company: "Co-founded by Jeff Huber (CEO) and Anton Troynikov, in San Francisco. An $18M seed led by Quiet Capital in April 2023; no later round found.",
    howItWorks: "Open source runs embedded, single-node or distributed. Chroma Cloud is a Rust engine on object storage: a distributed write-ahead log, compactor nodes that build indexes and write them to S3, and query nodes that serve from memory and SSD caches. It supports vector, sparse, full-text (trigram and regex) and metadata search, and is built for millions of small collections.",
    status: "Chroma Cloud is available on AWS and GCP, with BYOC for enterprise. It launched a research preview of agent memory, called Foundation, around August 2026.",
    pricing: "Usage-based: writes $2.50 per GiB, storage $0.33 per GiB-month, plus query and network charges. Team plan $250 a month. These are vendor list prices.",
    customers: "Capital One, UnitedHealthcare, Mintlify and Weights & Biases (logos on Chroma's homepage).",
    strengths: [
      "The easiest developer onboarding in the category.",
      "Object-storage design, so it's cheap for many small collections.",
      "Apache 2.0 throughout.",
      "Regex full-text search suits code search.",
    ],
    weaknesses: [
      "Seed-stage funding and a limited enterprise track record.",
      "Built for retrieval collections, not versioned multimodal tables.",
      "No open table format other engines can query in place.",
      "Few regions for multi-tenant cloud.",
    ],
    whereItWins: "Prototyping, per-user or per-repo agent memory across millions of small collections, and code search.",
    whereLanceWins: "Large multimodal datasets, training pipelines, versioning and time travel, and SQL analytics over the same data.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Chroma is also embedded, open source and on object storage. What's the difference?",
      a: "The deployment shape is similar, but the scope is different. Chroma is a retrieval index for AI apps. Lance is a format and engine for all of the AI data, with fast random access for training and integrations with Spark, Ray and DuckDB.",
    },
    vendorClaims: ["'Up to 10x cheaper.'", "Monthly download figures of 11M and 15M, both shown on the site."],
    uncertain: ["When Chroma Cloud went GA. Sources disagree between August 2025 and early 2026."],
    sourceIds: ["chroma-serverless", "chroma-pricing"],
  },
  {
    id: "pgvector", asOf: "2026-09",
    company: "pgvector is an open-source extension led by Andrew Kane. pgvectorscale comes from Tiger Data, which was Timescale until June 2025. Postgres itself consolidated in 2025: Databricks bought Neon for about $1B, and Snowflake bought Crunchy Data.",
    howItWorks: "pgvector adds vector, halfvec, sparsevec and bit types with HNSW and IVFFlat indexes inside Postgres. Filtering is plain SQL, with known recall issues when filtering after the search. pgvectorscale adds a disk-based StreamingDiskANN index with binary quantization, so the index doesn't have to fit in RAM. pg_textsearch adds BM25, so hybrid search can be done in SQL. Storage is Postgres pages on block storage, not object storage.",
    status: "pgvector 0.8.6 shipped on July 29, 2026. Most of its 2026 releases were fixes for HNSW vacuum and index corruption. pgvectorscale 0.9.1 (September 2026) hardened DiskANN against memory-safety bugs.",
    pricing: "The extensions are free; you pay for the Postgres host.",
    strengths: [
      "'Just use Postgres': transactions, joins, SQL, and existing backups and operations.",
      "Pre-installed on RDS, Cloud SQL, Azure, Supabase and Neon.",
      "Hybrid search in SQL.",
      "Backed indirectly by Databricks and Snowflake through their Postgres acquisitions.",
    ],
    weaknesses: [
      "A row store on block storage: expensive and slow for billions of vectors or terabytes of blobs, and poor for columnar scans and training loads.",
      "Index builds and vacuum are memory-heavy and fragile at scale.",
      "No object-storage tiering and no dataset versioning.",
      "Scales vertically, or by sharding with extra tools.",
    ],
    whereItWins: "Up to tens of millions of vectors, where transactional data and embeddings are queried together and the team already runs Postgres.",
    whereLanceWins: "Very large multimodal data, cheap object storage, training and feature pipelines, columnar analytics and blobs.",
    fourNeeds: { scans: "partial", random: "strong", blobs: "weak", columns: "partial" },
    objection: {
      q: "Why not just use pgvector? We already run Postgres.",
      a: "For an app with a few million embeddings next to transactional data, you should. Lance matters when the data is large, multimodal and reused for training and analytics. At that point a row store on SSD costs too much and can't feed GPUs.",
    },
    vendorClaims: ["Tiger Data: 2,000+ customers and 3M+ active databases (as of June 2025)."],
    sourceIds: ["pgvector-changelog", "pgvectorscale-091", "infoworld-crunchy", "cnbc-neon"],
  },
  {
    id: "turbopuffer", asOf: "2026-09",
    company: "Founded in 2023 by former Shopify engineers Simon Hørup Eskildsen (CEO) and Justine Li. It raised under $1M from Lachy Groom in 2024, then a round with Thrive Capital in December 2025 of undisclosed size. BetaKit counted 22 staff in December 2025; its site now says 50+.",
    howItWorks: "Rust binaries over object storage with a memory and NVMe cache. Writes go to a write-ahead log on object storage, batched to one entry per namespace per second, so write latency is high but throughput is too. The vector index is SPFresh, a centroid-based design that limits round trips to object storage. It also has BM25 full-text, hybrid search and filtering, with strong consistency by default. The docs say namespaces can reach 256 TB.",
    status: "Growing fast. Sacra estimated about $100M in annualized revenue in March 2026. That is an estimate, not a company figure. The vendor says it has over a trillion documents in production.",
    pricing: "Usage-based on storage, writes and queries, with plan minimums. Enterprise is $4,096 a month with single-tenant, BYOC and customer-managed keys. These are vendor list prices.",
    customers: "Anthropic, Notion, Linear, Atlassian and The New York Times (turbopuffer's site). Cursor per BetaKit and Sacra. Notion moved from Pinecone, reportedly in 2024.",
    strengths: [
      "Object-storage economics proven with marquee AI customers.",
      "Extremely capital-efficient, with fast revenue growth.",
      "Full-text, vector and hybrid search with strong consistency.",
      "A simple API for many per-user or per-repo namespaces.",
    ],
    weaknesses: [
      "Closed-source SaaS only, with no embedded mode or open format.",
      "Stores documents, vectors and attributes for search, not training data, features, blobs or versioned datasets.",
      "Write latency and cold-query latency until the cache warms.",
      "Customer concentration risk.",
    ],
    whereItWins: "Very large managed multi-tenant search, like code search or per-workspace RAG, where the buyer wants a hosted service with no operations.",
    whereLanceWins: "An open format with an embedded mode, training and feature pipelines, multimodal blobs, versioned datasets, and data in the customer's own bucket readable by other engines.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "turbopuffer has the same object-storage design, with Cursor and Anthropic as customers. Why LanceDB?",
      a: "Both bet on object storage, which confirms the thesis. turbopuffer is a closed search service. Lance is an open format where the same versioned table holds the raw data and feeds training and analytics, and you don't need one vendor's API to read your own data.",
    },
    vendorClaims: ["'10x cheaper.'", "Sub-10 ms p50 latency when warm.", "1T+ documents, 10M+ writes and 25,000+ queries per second."],
    uncertain: ["The size and valuation of the December 2025 round.", "Revenue, which is a Sacra estimate."],
    sourceIds: ["tpuf-about", "tpuf-arch", "tpuf-pricing", "betakit-tpuf", "sacra-tpuf"],
  },
  {
    id: "s3-vectors", asOf: "2026-09",
    company: "AWS.",
    howItWorks: "A new S3 bucket type, the vector bucket, that holds vector indexes AWS builds and searches for you, with no clusters. Each vector can carry up to 50 metadata keys for filtering. Latency is under a second for infrequent queries and around 100 ms for frequent ones. There is no native full-text or hybrid search; that comes through OpenSearch.",
    status: "GA on December 2, 2025, with 2 billion vectors per index and 10,000 indexes per bucket. It expanded to 31 regions in March 2026. In June 2026 AWS cut query charges by up to 80% for indexes above 10 million vectors, and raised results per query to 10,000. It integrates with Bedrock Knowledge Bases, OpenSearch and SageMaker Unified Studio.",
    pricing: "In us-east-1: uploads $0.20 per GB, storage $0.06 per GB-month, queries $2.50 per million plus a data-processed charge tiered by index size. These are vendor list prices; re-check the tiers before quoting them.",
    customers: "March Networks, MIXI and BMW (AWS feature page).",
    strengths: [
      "The least effort, and likely the lowest storage cost, for AWS shops.",
      "Native to S3: IAM, durability and regions come for free.",
      "High limits and fast regional expansion.",
      "A built-in tiered design with OpenSearch as the hot tier.",
    ],
    weaknesses: [
      "Vectors plus metadata only. No source data, blobs, features, SQL or training access, and no open format for other engines.",
      "No full-text or hybrid search, and around 100 ms latency at best.",
      "AWS only.",
      "No versioning or time travel.",
    ],
    whereItWins: "RAG on AWS through Bedrock Knowledge Bases, cold vector tiers, and cost-driven buyers with modest latency needs.",
    whereLanceWins: "Multi-cloud and on-premises, hybrid and full-text search, rich SQL filtering, multimodal blobs, training pipelines and versioning. Lance on S3 gets the same storage economics in an open format.",
    fourNeeds: { scans: "weak", random: "partial", blobs: "weak", columns: "weak" },
    objection: {
      q: "Won't S3 Vectors commoditize LanceDB? Both are vectors on S3.",
      a: "S3 Vectors commoditizes the simplest case: store embeddings and run nearest-neighbour search. Lance on S3 is a full table format holding the media, text, features and embeddings together, versioned, and it serves search, SQL and training from the same files. S3 Vectors is a good cold vector tier, not an AI data lake.",
    },
    vendorClaims: [
      "'Up to 90%' lower total cost than specialized vector databases.",
      "Query charges down by up to 80% for large indexes.",
    ],
    sourceIds: ["aws-s3v-ga", "aws-s3v-blog", "aws-s3v-regions", "aws-s3v-price-cut", "aws-s3v-topk", "aws-s3-pricing"],
  },
  {
    id: "search-incumbents", asOf: "2026-09",
    howItWorks: "Elasticsearch's DiskBBQ is an IVF-style index of quantized, clustered partitions read from disk, and 9.4 sped up restrictive filters. OpenSearch builds indexes on GPUs and can use S3 Vectors as its storage engine. MongoDB bought Voyage AI in February 2025 and added automatic embedding with Voyage models in 2026. Vespa does tensor ranking and real-time hybrid search at web scale. Google's Agent Retrieval, formerly Vector Search 2.0, stores vectors, metadata and content together.",
    status: "All are active and shipping vector features in 2026. Perplexity runs on Vespa. Microsoft's vector search lives in Azure AI Search and Cosmos DB; no native Azure Blob vector feature was found.",
    strengths: [
      "Already deployed at the customer, with mature operations.",
      "Mature BM25 and hybrid search (Elastic, OpenSearch, Vespa).",
      "Vectors next to operational documents (MongoDB).",
    ],
    weaknesses: [
      "Search and operational clusters on local disk, not training data stores.",
      "Blobs and training reads are out of scope.",
      "Vector search is a feature of a larger product.",
    ],
    whereItWins: "Wherever the customer already runs them and retrieval is one feature of an existing app.",
    whereLanceWins: "As the source-of-truth table that search indexes are built from and that training reads, for large multimodal data on object storage.",
    fourNeeds: { scans: "partial", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "We already run Elastic, or MongoDB, and it does vectors now. Why add anything?",
      a: "Keep it for the app. The question is where the images, features and training sets live and how they stay in sync. Lance is the versioned table underneath, and search clusters can be one consumer of it.",
    },
    sourceIds: ["elastic-diskbbq", "mongodb-voyage", "vespa-perplexity", "google-agent-retrieval"],
  },
];
