import type { CompetitorDetail } from "./types";

/** Platforms, direct multimodal rivals, partners and training-data formats.
 *  Researched September 2026. */
export const platformDetails: CompetitorDetail[] = [
  {
    id: "databricks-snowflake", asOf: "2026-09",
    company: "Databricks raised $5B at a $190B valuation in August 2026, led by Coatue. It reports a revenue run-rate above $7B, growing more than 80% a year, and says 20,000+ organizations use it. Snowflake is public. It reported $1.49B in product revenue for the quarter ending July 2026, up 37%, with 126% net revenue retention.",
    howItWorks: "Databricks: vector search (current docs call it 'AI Search') syncs HNSW indexes from Delta tables. Storage-optimized endpoints go past a billion vectors at around 250 ms. Unity Catalog governs files through Volumes, and the new FILE type (beta) references PDFs, images, audio and video from inside Delta and Iceberg tables. Lakebase is serverless Postgres from the Neon acquisition. MosaicML Streaming feeds training from shards. Snowflake: Cortex AI Functions run LLM operators such as AI_FILTER, AI_EMBED and AI_TRANSCRIBE as SQL over FILE values that reference staged media. Cortex Search is managed hybrid search over tables, and Horizon Catalog runs on Apache Polaris.",
    status: "Databricks made managed Iceberg and Iceberg v3 GA in May 2026, launched the FILE type at Data + AI Summit 2026, and made Lakebase GA on AWS and Azure. mosaicml-streaming hasn't had a release since July 2025. Snowflake made Iceberg v3 GA, launched Cortex Training (custom model training on managed GPUs) at Summit 2026, and bought Crunchy Data (2025), Observe (early 2026) and Natoma (announced May 2026).",
    customers: "Databricks: Adidas, AT&T, Bayer, Block, Mastercard, Rivian, Unilever (its August 2026 release).",
    strengths: [
      "The largest installed bases and procurement relationships in data.",
      "One governance plane over tables, files, models and vector indexes.",
      "Both now hedge on Iceberg, so format interop is less of a lever against them.",
      "Billion-scale vector search and SQL-native multimodal inference.",
      "Snowflake now offers managed GPU training.",
    ],
    weaknesses: [
      "Vector search is a synced copy, not an index versioned with the table.",
      "FILE types on both are pointers; the media still sits outside the table format.",
      "Iceberg and Delta on Parquet keep the random-access and backfill limits.",
      "Databricks' training path is a separate shard copy in a library that has slowed.",
      "Consumption pricing for AI functions over large media is expensive.",
    ],
    whereItWins: "A buyer already standardized on either platform, whose AI data is mostly documents and text for RAG and BI, and who values one bill and one governance plane over training throughput.",
    whereLanceWins: "Petabytes of images, video or sensor data that must be scanned, sampled at random for training, searched and extended with new feature columns, all from one open versioned table that Spark can still read.",
    partnerOrRival: "Both. The largest rival for AI data budget, and also the environment Lance tables often sit next to.",
    fourNeeds: { scans: "strong", random: "partial", blobs: "partial", columns: "partial" },
    objection: {
      q: "Databricks has a FILE type and billion-scale vector search now. Why add LanceDB?",
      a: "FILE governs references to blobs, and the vector index is a synced copy. Neither makes Parquet good at random access or cheap per-row backfills. Lance keeps blobs, embeddings, indexes and features in one versioned table that Spark can still read, so it complements the catalog rather than replacing it.",
    },
    vendorClaims: [
      "Databricks storage-optimized endpoints: 'up to 7x cheaper' per vector and '10 to 20x faster' indexing.",
      "Snowflake AISQL: up to 70% lower run time on FILTER and JOIN (internal benchmarks).",
    ],
    uncertain: ["Whether 'AI Search' is a formal rename of Databricks Vector Search.", "Any Lance support on either platform; none was found."],
    sourceIds: ["databricks-190b", "databricks-vs-docs", "databricks-file-type", "databricks-iceberg-ga", "cnbc-neon", "pypi-mosaic-streaming", "snowflake-q2fy27", "snowflake-multimodal", "constellation-summit26", "infoworld-crunchy"],
  },
  {
    id: "vast", asOf: "2026-09",
    company: "Founder and CEO Renen Hallak. VAST raised about $1B at a $30B valuation, led by Drive Capital with Access Industries, and with NVIDIA participating. It was reported in March 2026 and formally announced in April. More than $500M of the round was secondary.",
    howItWorks: "An all-flash storage platform with a disaggregated, shared-everything design. It combines file and object storage, VAST DataBase (a transactional and analytical table store inside the storage system, with vectors as a type), event-triggered functions and a global namespace. InsightEngine runs NVIDIA embedding models on write and GPU vector search. CNode-X (February 2026) runs the platform on NVIDIA GPU servers with a GPU SQL engine.",
    status: "VAST Forward in February 2026 launched CNode-X, a GPU SQL engine and a Kubernetes control plane it also calls Polaris, unrelated to Apache Polaris. It signed a $1.17B deal with CoreWeave in November 2025.",
    customers: "CoreWeave, Lowe's, the U.S. Air Force, Cursor, Mistral AI, JPMorganChase and Crusoe (VAST's April 2026 release).",
    strengths: [
      "Owns the storage tier in GPU clouds and neoclouds.",
      "Scale and throughput, now GPU-accelerated.",
      "One system for files, objects, tables, vectors and triggers.",
      "Strong reported financials.",
    ],
    weaknesses: [
      "Proprietary and tied to VAST's platform; the data isn't in an open, portable table format.",
      "VAST DataBase needs VAST connectors; PyTorch, Ray and DuckDB can't read it directly.",
      "High entry cost, aimed at large infrastructure buyers.",
      "No sign of a git-like dataset versioning or zero-copy column evolution model for ML teams.",
    ],
    whereItWins: "GPU clouds and large enterprises buying an on-premises or neocloud storage platform that want storage, database and vector search from one vendor.",
    whereLanceWins: "Teams native to cloud object storage that want an open format and an Apache-licensed core, portable across S3, GCS and Azure, with training loaders, feature backfills and versioned datasets. Lance can also run on VAST's S3-compatible storage.",
    partnerOrRival: "Both. Lance runs on VAST's S3 endpoint, but VAST DataBase and InsightEngine compete for the 'AI data layer' story.",
    fourNeeds: { scans: "strong", random: "strong", blobs: "partial", columns: "partial" },
    objection: {
      q: "VAST claims trillion-vector search and a database built into storage. Why not use that?",
      a: "VAST is excellent storage, but its database is proprietary and tied to its platform. Lance is an open format that runs on any object store, including VAST's, so customers get the performance without handing their data format to a storage vendor.",
    },
    vendorClaims: ["$4B+ cumulative bookings and $500M+ committed ARR.", "Trillion-vector scale with sub-second search."],
    sourceIds: ["vast-series-f", "bf-vast-nvidia", "bf-vast-coreweave", "vast-database", "tracxn"],
  },
  {
    id: "hyperscaler-lakehouses", asOf: "2026-09",
    company: "Google Cloud and Microsoft.",
    howItWorks: "BigQuery ObjectRef columns reference Cloud Storage objects from inside tables, including managed Iceberg. AI.GENERATE_EMBEDDING creates multimodal embeddings, and BigQuery vector search indexes them. Vertex's successor, Agent Retrieval, keeps vectors, metadata and content together. Microsoft Fabric stores Delta tables in OneLake. Its AI Functions accept image and PDF paths, and Azure AI Search indexes OneLake files.",
    status: "Google made ObjectRefs GA and opened managed Iceberg to third-party engines in April 2026. Fabric's multimodal AI Functions are in preview.",
    strengths: [
      "The default choice inside each cloud.",
      "Serverless SQL over structured and unstructured data.",
      "Built-in models (Gemini) and Microsoft 365 integration.",
    ],
    weaknesses: [
      "Media are pointers to objects, not columnar blobs.",
      "Vector indexes live in separate services.",
      "Tied to one cloud each.",
      "No training loader path.",
    ],
    whereItWins: "Teams native to one cloud doing multimodal SQL analysis or document AI.",
    whereLanceWins: "Multi-cloud training and feature engineering over large media, with open-format random access.",
    fourNeeds: { scans: "strong", random: "partial", blobs: "partial", columns: "partial" },
    objection: {
      q: "Google now ships a multimodal lakehouse. Isn't this commoditized?",
      a: "It's an Iceberg table plus pointers to objects. Lance stores the bytes, embeddings and indexes in one versioned table with fast random access, which is what training and search need, and it runs on every cloud.",
    },
    sourceIds: ["google-lakehouse-2026", "google-agent-retrieval", "fabric-multimodal"],
  },
  {
    id: "training-formats", asOf: "2026-09",
    howItWorks: "WebDataset streams tar shards in sequence and shuffles at shard level. TFRecord is a length-prefixed protobuf record file for tf.data. MosaicML Streaming (MDS) uses sharded binaries with index files, deterministic ordering and mid-epoch resume. NVIDIA DALI is a GPU decode and augmentation pipeline, not a storage format. torchdata now centers on StatefulDataLoader after deprecating DataPipes. LitData converts data into chunks for streaming.",
    status: "DALI (2.3.0, August 2026) and LitData are the most active. WebDataset reached 1.0 in 2025. MosaicML Streaming hasn't had a release since July 2025, and torchdata since February 2025. TFRecord is maintained as part of TensorFlow.",
    strengths: [
      "Sequential throughput for full-epoch scans.",
      "Simple streaming from object storage.",
      "Deterministic resume (MDS, LitData).",
      "GPU decoding (DALI).",
    ],
    weaknesses: [
      "Write-once copies: no lookup by key, no filtering, no versioning and no indexes.",
      "Adding a column or changing the sampling mix means re-sharding.",
      "Curation happens in another system, and its results have to be exported again.",
    ],
    whereItWins: "Fixed datasets trained in repeated full sequential epochs on established pipelines. DALI is complementary: it can decode bytes read from Lance.",
    whereLanceWins: "Iterative curation (filter, search, dedupe, sample by predicate), then training from the same versioned table. Random sampling, adding labels or embeddings without rewriting, and an NVMe cache to close the sequential-throughput gap.",
    partnerOrRival: "Rivals as the storage format for training data. DALI and StatefulDataLoader are complementary loaders.",
    fourNeeds: { scans: "partial", random: "weak", blobs: "strong", columns: "weak" },
    objection: {
      q: "Frontier labs train on WebDataset or MDS shards at huge scale. Why would they switch?",
      a: "Sequential shards are great for fixed epochs, but every curation change means re-sharding a full copy. Lance lets teams curate, version and randomly sample the same table they search and backfill, and a local NVMe cache recovers streaming throughput. The pitch is removing the export step, not beating tar on raw sequential reads.",
    },
    vendorClaims: ["LitData: 'up to 20x' faster training throughput."],
    sourceIds: ["pypi-webdataset", "pypi-mosaic-streaming", "pypi-dali", "pypi-torchdata", "litdata-gh"],
  },
  {
    id: "spiral", asOf: "2026-09",
    company: "Founder and CEO Will Manning. $22M across a seed and a Series A, from Amplify Partners and General Catalyst, announced September 2025.",
    howItWorks: "A database and platform on the Vortex format: native to object storage, with branches and tags for versioning, queries in place, and GPU data loading using NVIDIA's hardware video decoding and CUDA.",
    status: "Early access, onboarding a few teams at a time. It calls itself a multimodal data intelligence platform for ML and robotics teams.",
    customers: "Chef Robotics, Skild AI and Figure AI (Spiral's site).",
    strengths: [
      "The closest architectural rival: a new open format with claimed random-access gains, plus a platform on top.",
      "Neutral Linux Foundation governance for the format.",
      "Robotics customers, which is LanceDB's growth market too.",
    ],
    weaknesses: [
      "Early access only.",
      "No indexes in the format, and a smaller ecosystem than Lance.",
      "Vortex's Iceberg integration isn't merged.",
    ],
    whereItWins: "Robotics teams attracted to Vortex's compression and scan speed, and willing to be early.",
    whereLanceWins: "Maturity, built-in indexes, blob handling, column evolution, a production search engine, and integrations with Hugging Face, Ray, Daft and Spark.",
    partnerOrRival: "A direct rival on both format and platform.",
    fourNeeds: { scans: "strong", random: "strong", blobs: "partial", columns: "partial" },
    objection: {
      q: "Vortex claims 100 times Parquet's random access, the same pitch as Lance. What's the difference?",
      a: "Both beat Parquet on random access. Lance ships indexes, blob handling, column evolution and a production search engine today, with public petabyte-scale users. Spiral is in early access.",
    },
    vendorClaims: ["Parquet-level compression with 10 to 20 times faster scans and 100 to 200 times faster random access."],
    uncertain: ["Headcount, a general availability date, and any funding since September 2025."],
    sourceIds: ["spiral-site", "spiral-announce", "gunder-spiral", "lf-vortex"],
  },
  {
    id: "deeplake", asOf: "2026-09",
    company: "Activeloop, founded by Davit Buniatyan (Y Combinator S18). It raised an $11M Series A in March 2024, about $20M in total. No later round was found.",
    howItWorks: "A columnar 'tensor' format on object storage with lazy NumPy-style indexing, native compression, built-in PyTorch and TensorFlow loaders, versioning and its own query language. Deep Lake PG (December 2025) adds a serverless Postgres layer on top for SQL, transactions and vector search.",
    status: "It has repositioned repeatedly. Deeplake's site says 'the GPU database for the agentic era', while Activeloop now brands itself 'continual learning infrastructure'. Apache 2.0, with about 9,200 GitHub stars.",
    customers: "Intel, Bayer, Matterport and CoStar Group (Activeloop's site).",
    strengths: [
      "An early mover on versioned multimodal datasets with streaming loaders.",
      "LangChain and LlamaIndex integrations.",
      "A Postgres interface lowers the adoption barrier.",
    ],
    weaknesses: [
      "A small, thinly funded company that keeps changing its positioning.",
      "Its format is read by far fewer engines than Lance.",
      "Little independent benchmark evidence.",
    ],
    whereItWins: "Small teams that want one Postgres-compatible endpoint for agent memory and multimodal retrieval.",
    whereLanceWins: "Ecosystem breadth, Hugging Face integration, petabyte-scale references and an open, engine-neutral format.",
    partnerOrRival: "A direct rival.",
    fourNeeds: { scans: "partial", random: "strong", blobs: "strong", columns: "partial" },
    objection: {
      q: "Deep Lake did versioned multimodal datasets with PyTorch loaders first. What's different?",
      a: "Lance is designed as an open table format that many engines read natively, with random access, vector and full-text indexes and zero-copy column evolution in the format. Deep Lake has moved toward a service and pivoted toward agents.",
    },
    vendorClaims: ["1.5 times cheaper than Snowflake and up to 3 times cheaper than Databricks on TPC-H.", "Matterport cut data prep time by up to 80%."],
    uncertain: ["Headcount and any 2025 or 2026 funding.", "Compatibility details of the Deep Lake 4.0 format."],
    sourceIds: ["deeplake-gh", "deeplake-pg", "activeloop-series-a", "gradientflow-mmlh"],
  },
  {
    id: "pixeltable", asOf: "2026-09",
    company: "Founded by Marcel Kornacker (creator of Apache Impala, co-creator of Parquet), Aaron Siegel and Pierre Brunelle. A $5.5M seed led by The General Partnership, announced December 2024; Wes McKinney is an angel.",
    howItWorks: "A Python library in which tables have typed image, video, audio and document columns. Computed columns, such as model calls and UDFs, update incrementally when data changes, and embedding indexes are declared on columns. Recent versions can serve an app over HTTP. Gradient Flow describes it as built on Postgres and pgvector.",
    status: "Active: 0.7.8 shipped on September 16, 2026. Pixeltable Cloud is in limited beta. Apache 2.0.",
    strengths: [
      "An elegant declarative, incremental model with lineage.",
      "Founders with real pedigree in formats and databases.",
      "Combines orchestration, storage, vector index and serving for app builders.",
    ],
    weaknesses: [
      "Built as an application backend, not for petabyte scans or training-throughput reads.",
      "Not an open on-disk format other engines can read.",
      "Very early commercially, with no named customers.",
    ],
    whereItWins: "A small team building a multimodal RAG or agent app that wants a batteries-included Python backend.",
    whereLanceWins: "Billions of rows and petabytes, training pipelines, multi-engine access, and distributed backfills with Geneva on Ray.",
    partnerOrRival: "A rival for mindshare. No Lance integration was found.",
    fourNeeds: { scans: "partial", random: "partial", blobs: "partial", columns: "strong" },
    objection: {
      q: "Pixeltable's computed columns sound like Geneva. Why pay for LanceDB?",
      a: "Same idea: declarative, incremental derived columns. Geneva runs those backfills distributed on Ray over an open columnar format built for petabytes. Pixeltable targets a single application backend.",
    },
    vendorClaims: ["Up to 80% less infrastructure code and 50% less wasted compute."],
    uncertain: ["The current storage backend. Postgres comes only from Gradient Flow's description."],
    sourceIds: ["pixeltable-seed", "pixeltable-pypi", "gradientflow-mmlh"],
  },
  {
    id: "aperturedb", asOf: "2026-09",
    company: "Founded in 2018 by Vishakha Gupta (CEO) and Luis Remis (CTO), both from Intel Labs. An $8.25M seed led by TQ Ventures in October 2024; Tracxn lists $11.2M in total.",
    howItWorks: "A graph-vector database. Metadata and annotations such as bounding boxes live in an in-memory property graph, vector search is FAISS-based, and images and video are stored natively with on-the-fly crop, resize and frame sampling. A JSON query language gives ACID transactions across data types. It is offered as a cloud service or self-managed.",
    status: "Active, with its Python SDK at 0.4.60 (June 2026) and messaging moving toward context graphs for agents.",
    customers: "Badger Technologies, Zippin, Jabil and Gracenote (ApertureData's site).",
    strengths: [
      "Graph, vector and media in one transactional engine.",
      "Good for relationship-heavy visual data in retail and manufacturing.",
      "Media preprocessing on the server.",
    ],
    weaknesses: [
      "A proprietary server, not an open format on object storage.",
      "A small, seed-stage company.",
      "An in-memory graph limits scale economics.",
      "Not built for petabyte scans or training throughput.",
    ],
    whereItWins: "Visual AI apps that need graph queries over annotations plus similarity search, at moderate scale.",
    whereLanceWins: "Scale, open format, analytics and training reads, access from many engines, and object-storage cost.",
    partnerOrRival: "A rival.",
    fourNeeds: { scans: "weak", random: "strong", blobs: "strong", columns: "partial" },
    objection: {
      q: "ApertureDB does graph and vector search over images. Doesn't Lance lack the graph?",
      a: "Lance models relationships as columns and joins through engines like DuckDB or Spark, and it's built for scale and open access. A buyer whose core need is graph traversal over annotations may prefer a graph-vector database; most training and search workloads don't need one.",
    },
    vendorClaims: ["2 to 10 times faster KNN and under 10 ms vector search.", "35 times faster multimodal data access."],
    sourceIds: ["aperture-seed", "aperture-docs"],
  },
  {
    id: "daft", asOf: "2026-09",
    company: "Eventual, co-founded by Sammy Sidhu and Jay Chia, both from Lyft Level 5. $30M in total: a seed led by CRV and a $20M Series A led by Felicis in June 2025, when it had 18 people.",
    howItWorks: "A distributed DataFrame engine with a Rust core and a Python API, native multimodal types (images, URLs, tensors, embeddings) and model UDFs. It runs locally or on Ray, and Flotilla is its newer distributed engine. It reads and writes Lance natively, including reading specific versions, pushing filters down, vector search and merge_columns.",
    status: "The 2026 roadmap covers 100 TB shuffles, checkpointing and Kubernetes. Eventual's site now pitches scenario mining and data curation for robot fleet data, a move toward physical AI with Daft as the open-source engine underneath.",
    customers: "Amazon, CloudKitchens, Essential AI and Together AI (Eventual, June 2025).",
    strengths: [
      "A fast, multimodal-aware processing engine.",
      "Deep Lance and Unity Catalog integrations.",
      "Strong at batch inference and ETL over media.",
    ],
    weaknesses: [
      "Compute, not storage: no format, versioned table or index of its own.",
      "The robotics pivot narrows its focus.",
    ],
    whereItWins: "Distributed transformation and inference over multimodal data once storage is chosen, and robotics scenario mining.",
    whereLanceWins: "Persistent storage, search, versioning and training reads. Daft is often the engine writing to Lance.",
    partnerOrRival: "Mostly a partner at the engine layer. Eventual's robotics curation product could overlap with LanceDB Enterprise in physical AI accounts.",
    objection: {
      q: "Daft claims to be 18 times faster than Spark and Ray Data. Does it replace Geneva?",
      a: "Daft is an execution engine. Geneva is feature engineering bound to the Lance table, with versioned, incremental column backfills. They compose: Daft reads and writes Lance and can merge columns, so it's a choice of orchestration, not of storage.",
    },
    vendorClaims: ["Flotilla 'up to 18x faster than Spark and Ray Data'.", "2 PB a day processed at Amazon."],
    sourceIds: ["eventual-30m", "daft-lance", "daft-roadmap"],
  },
  {
    id: "ray", asOf: "2026-09",
    company: "Nscale, a GPU cloud, agreed to acquire Anyscale on July 30, 2026, with closing expected in the second half of 2026. The release doesn't give a price; Bloomberg reported $1.65B. Ray itself was donated to the PyTorch Foundation in October 2025, isn't part of the deal, and Nscale is joining the foundation.",
    howItWorks: "Ray Data is a streaming, distributed data-processing library that mixes CPU and GPU stages and runs batch inference through vLLM and SGLang. It has a native read_lance with version and column selection, and the lance-ray project adds distributed writes.",
    status: "Active. LanceDB and Exa had a joint session planned at Ray Summit in August 2026.",
    customers: "Coinbase, Bedrock Robotics and Runway (Anyscale's release). ByteDance runs multimodal batch inference on Ray.",
    strengths: [
      "The standard distributed runtime for AI data pipelines and RL.",
      "Scheduling across mixed CPU and GPU hardware.",
      "Large open-source adoption.",
    ],
    weaknesses: ["Not a storage layer: no format, versioning, indexes or catalog."],
    whereItWins: "Compute orchestration. It's never an either-or with Lance.",
    whereLanceWins: "Persistence, random access and search. Geneva runs on Ray.",
    partnerOrRival: "A partner. Watch whether Nscale bundles Anyscale with its own GPU cloud.",
    objection: {
      q: "A GPU cloud is buying Anyscale. Is depending on Ray a risk for LanceDB?",
      a: "Ray is governed by the PyTorch Foundation, and Nscale says it will support it there. Geneva depends on open-source Ray, not on Anyscale's product.",
    },
    sourceIds: ["nscale-anyscale", "bloomberg-anyscale", "ray-read-lance", "lance-ray-gh"],
  },
  {
    id: "huggingface", asOf: "2026-09",
    company: "Nvidia agreed on September 3, 2026 to acquire Hugging Face for $12.93B. Jensen Huang said the Hub 'will remain an open platform for the entire AI ecosystem', supporting models from every builder across clouds and accelerators.",
    howItWorks: "The Hub stores large files on Xet, which replaced Git LFS with content-defined chunking and global deduplication on S3. The datasets library streams Parquet and other formats. Lance is a documented Hub format: you can scan, filter, fetch blobs and run vector search on Lance datasets directly from hf:// paths, and load_dataset streaming works on them.",
    status: "Lance support was announced around February 2026, and a lance-format organization publishes datasets such as laion-1m and OpenVid-1M. The Nvidia deal is pending; no close date is given in Nvidia's post.",
    strengths: [
      "The default channel for sharing AI datasets and models.",
      "Storage efficient through deduplication.",
      "A huge community, soon with Nvidia's backing.",
    ],
    weaknesses: [
      "A distribution and versioning layer, not a query engine or table format.",
      "HF's docs warn that heavy vector queries and blob streaming against the Hub hit rate limits, and recommend downloading locally.",
    ],
    whereItWins: "Publishing and sharing datasets and models.",
    whereLanceWins: "Querying, training reads and feature evolution. Lance is what makes Hub datasets searchable in place.",
    partnerOrRival: "A partner. The Hub officially documents Lance, and Lance datasets carry their indexes onto it.",
    objection: {
      q: "Doesn't Nvidia buying Hugging Face threaten Lance's distribution?",
      a: "Nvidia has said publicly that the Hub stays open, and Lance support is in HF's own docs. The Hub distributes; Lance makes the data queryable. A bigger, Nvidia-backed Hub is more reach for Lance datasets, not less.",
    },
    uncertain: ["When the Nvidia deal closes."],
    sourceIds: ["nvidia-hf", "hf-lance-docs", "lancedb-hf-blog", "hf-xet"],
  },
];
