import type { CompetitorDetail } from "./types";

/** Table formats, file formats and catalogs. Researched September 2026. */
export const formatDetails: CompetitorDetail[] = [
  {
    id: "iceberg", asOf: "2026-09",
    company: "An Apache project with no single owner. Engineers from Google, Apple, Snowflake, Databricks, Microsoft, Netflix and LinkedIn worked on the v4 design at Iceberg Summit 2026. Release 1.11.0 had more than 1,000 commits from over 200 contributors.",
    howItWorks: "A tree of metadata over immutable data files, which are Parquet by default. Each commit writes a new metadata.json, manifest list and manifests, and the catalog swaps a pointer to it. Puffin sidecar files hold statistics, and in v3 they also hold deletion vectors. Release 1.11.0 added a pluggable File Format API, so formats other than Parquet, ORC and Avro can register.",
    status: "Java 1.11.0 shipped on May 19, 2026, and v3 is no longer experimental. v3 support by engine: Snowflake GA on May 7, 2026, though new tables still default to v2. Databricks moved from Public Preview in April to GA on May 28, 2026. EMR, Glue, S3 Tables, Trino and DuckDB 1.5.3 support it. BigQuery reads v3 but cannot write it, and Athena still rejects v3 tables. For v4, relative paths and new content stats passed in May 2026. Single-file commits and an adaptive metadata tree are in active design. Efficient column updates, meaning column groups evolved independently, are the most debated topic, with no consensus. A dense vector type is being discussed on the dev list, and a PR adding Vortex as a data file format has been open since April 2026. ByteDance described an internal system, Magnus (VLDB 2025), that extends Iceberg with a blob format, wide-table optimizations and vector and inverted indexes. Large AI shops are adding these features to Iceberg themselves.",
    strengths: [
      "The neutral default table format. Snowflake, Databricks, AWS, Google, Trino, DuckDB and Spark all read it.",
      "A broad REST catalog ecosystem: Polaris, Unity, Glue, S3 Tables, BigLake.",
      "v3 added deletion vectors, row lineage, VARIANT, geospatial types and nanosecond timestamps.",
      "The File Format API opens a door to data files that aren't Parquet.",
      "Vendor-neutral governance at the Apache Software Foundation.",
    ],
    weaknesses: [
      "Every commit writes several metadata files, which is heavy for frequent small commits. Single-file commits are still v4 design work.",
      "No agreed way to add a per-row column, such as a new embedding, without rewriting files. It is the most contested v4 topic.",
      "No vector type, blob type or ANN index in the spec today.",
      "Parquet data files make point lookups and very wide values expensive, and neither the Lance nor the Vortex plug-in path has merged.",
      "v3 support is uneven: Athena has none, BigQuery is read-only and PyIceberg writes are limited.",
    ],
    whereItWins: "Enterprise analytics and BI across several engines and clouds, where the same table must be readable by Snowflake, Databricks, AWS and BigQuery. Also regulated shops that standardize on one open table format and catalog.",
    whereLanceWins: "Point reads by row ID for training shuffles and retrieval, vector and full-text indexes versioned with the table, per-row backfills that write only the new column, and blobs stored in the table. All of this ships in Lance today. In Iceberg it is v4 discussion.",
    fourNeeds: { scans: "strong", random: "weak", blobs: "weak", columns: "partial" },
    objection: {
      q: "Iceberg v4 is adding column groups, ANN-friendly stats and pluggable file formats. Won't that make Lance unnecessary?",
      a: "Those are proposals. Column updates have no consensus, and the Vortex PR is waiting on a process for admitting new formats. Even if they land, Iceberg would be adopting physical-layer ideas Lance already ships. Lance also works with the Iceberg world through Polaris, Gravitino and Unity Catalog, so it doesn't have to be one or the other.",
    },
    vendorClaims: [
      "'Up to 10x faster DML' with v3 deletion vectors (Snowflake and Databricks).",
    ],
    sourceIds: ["ice-1-11", "snowflake-v3-ga", "databricks-v3-preview", "databricks-iceberg-ga", "aws-v3-konishi", "duckdb-iceberg-153", "snowflake-v4-recap", "merced-v4-jul26", "iceberg-vortex-pr", "dremio-open-lakehouse-sep26", "magnus-vldb"],
  },
  {
    id: "delta", asOf: "2026-09",
    company: "A Linux Foundation project whose development is led mostly by Databricks. Delta Kernel, delta-rs and UniForm are part of it.",
    howItWorks: "An ordered JSON transaction log with Parquet checkpoints, over Parquet data files. Newer catalog-managed tables let the catalog ratify commits instead of the file log. Delta Kernel gives every engine the same protocol logic. UniForm writes Iceberg metadata alongside each Delta commit, so Iceberg readers can query the same files.",
    status: "4.2.0 (April 2026) made VARIANT GA and UniForm synchronous. 4.3 wrote Iceberg metadata atomically with the Delta commit. 4.4.0 (August 20, 2026) added Spark 4.2 support, identity columns and Unity Catalog Delta APIs in Kernel and Flink. Databricks' FILE type (beta, August 2026) stores pointers to unstructured files as a column in managed Delta and Iceberg tables.",
    strengths: [
      "Databricks' native format, with enormous production scale.",
      "UniForm gives Iceberg read compatibility without copying data.",
      "Delta Kernel standardizes connectors across Spark, Flink and DataFusion.",
      "VARIANT GA and catalog-managed commits.",
    ],
    weaknesses: [
      "Data files are Parquet only, with the same random-access and wide-blob limits.",
      "No vector type or ANN index in the open protocol. Vector search on Databricks is a separate service.",
      "The FILE type stores pointers, not bytes, and is beta.",
      "Adding a per-row derived column means rewriting Parquet files or keeping a separate table.",
      "In practice, closely tied to Databricks and Unity Catalog.",
    ],
    whereItWins: "Databricks-centric shops, Spark-heavy ETL and BI, and teams that want one governed platform from one vendor.",
    whereLanceWins: "Random access for training and serving, indexes in the table, blob bytes in the format rather than behind pointers, column addition without rewrites, and neutrality across engines outside Databricks.",
    fourNeeds: { scans: "strong", random: "weak", blobs: "weak", columns: "partial" },
    objection: {
      q: "Databricks now has a FILE type and UniForm. Why not keep everything in Delta?",
      a: "FILE stores pointers; the bytes still live in object storage outside the table format, and it's beta. Vector search and random access still depend on Parquet plus a separate service. Lance keeps the bytes, embeddings and indexes in one versioned format, and Spark on Databricks can still read it.",
    },
    sourceIds: ["delta-4-2", "delta-kernel-uc", "databricks-file-type", "databricks-uc-dais26"],
  },
  {
    id: "hudi", asOf: "2026-09",
    company: "An Apache project that began at Uber. Onehouse, founded in 2021 by Hudi creator Vinoth Chandar, sells it. Onehouse raised a $35M Series B led by Craft Ventures in June 2024, about $68M in total. No 2026 round was found.",
    howItWorks: "A table format with a commit timeline, copy-on-write and merge-on-read tables, and an internal metadata table holding record-level and secondary indexes. Hudi 1.2 added Lance as a base file format next to Parquet and ORC, plus VECTOR and BLOB types. BLOB values can be stored inline or out of line and are loaded lazily. Vector search is distributed brute-force KNN, and an ANN index such as IVF-PQ is planned.",
    status: "Hudi 1.2 was announced on June 7, 2026 with VECTOR, BLOB, VARIANT and Lance base files. Lance files, VECTOR and BLOB work from Spark only. RFC-100 covers unstructured data and Lance support; RFC-102 covers native vector search.",
    strengths: [
      "Strong upserts, change data capture and incremental processing, with record-level indexing.",
      "Several file formats, including Lance, under one transactional table.",
      "First-class VECTOR and BLOB types with lazy blob reads.",
      "Mature Flink streaming.",
    ],
    weaknesses: [
      "Brute-force vector search only, with no ANN index yet.",
      "The AI features are Spark-only today.",
      "Vector columns must be top-level, not nested.",
      "A smaller ecosystem than Iceberg or Delta, and Onehouse's last disclosed round was in 2024.",
    ],
    whereItWins: "Streaming lakehouses heavy on CDC and upserts, especially existing Hudi deployments that want embeddings and blobs in the same transactional table.",
    whereLanceWins: "ANN, full-text and scalar indexes today, engines beyond Spark (DuckDB, Ray, Trino), and Lance as the whole table format rather than only a file under Hudi's timeline.",
    fourNeeds: { scans: "strong", random: "partial", blobs: "partial", columns: "partial" },
    objection: {
      q: "Hudi 1.2 supports Lance files plus VECTOR and BLOB. Doesn't that make Hudi a superset of Lance?",
      a: "Hudi adopting Lance as a file format is an endorsement. But it gives up the Lance table layer: ANN indexes (Hudi does brute force), Lance's versioning and column-append model, and engines other than Spark. Brute-force search doesn't scale to interactive retrieval over billions of rows.",
    },
    sourceIds: ["hudi-1-2", "hudi-vector", "onehouse-series-b"],
  },
  {
    id: "parquet", asOf: "2026-09",
    company: "An Apache project with a broad community. The main implementations are parquet-java, Arrow C++, arrow-rs and C#.",
    howItWorks: "Rows are grouped into row groups, and each group holds column chunks split into pages. Nesting is encoded with Dremel repetition and definition levels. A Thrift footer, decoded as a whole, locates everything. Reading one row means finding its row group, then its page (using the page index if present), then decoding that page.",
    status: "It is being modernized. Float encoding ALP passed a vote in July 2026. FSST, a string encoding that allows random access, finished design review in August 2026. A working group is weighing a new FlatBuffers footer. A policy defining major versions (the 'Parquet 3' question) passed in August 2026. FIXED_SIZE_LIST for embeddings and a FILE logical type for unstructured payloads are proposed. parquet-java 1.18.0 (August 2026) shipped a silent data corruption bug, and a fix is in progress.",
    strengths: [
      "Supported by every engine.",
      "Excellent scan compression, which ALP and FSST will improve.",
      "Actively modernizing, now with a formal versioning policy.",
      "Neutral Apache governance.",
    ],
    weaknesses: [
      "Embeddings are stored as variable-length lists until FIXED_SIZE_LIST lands.",
      "The monolithic Thrift footer is costly on wide schemas.",
      "Random access decodes whole pages; FSST helps strings only.",
      "No first-class home for large blobs.",
      "Adding a column means rewriting the file.",
    ],
    whereItWins: "Interchange and archival, scan-heavy BI, and anywhere maximum engine compatibility matters more than latency.",
    whereLanceWins: "Point reads without decoding a page, fixed-size vectors today, blob columns, indexes stored with the data, and cheap new columns. Each is a 2026 proposal for Parquet and a shipped feature in Lance.",
    fourNeeds: { scans: "strong", random: "weak", blobs: "weak", columns: "weak" },
    objection: {
      q: "Parquet is adding ALP, FSST, fixed-size lists and a new footer. Won't it close the gap?",
      a: "Some of it, and that's good for everyone. But those changes land over years across many implementations and need every reader to upgrade; the versioning policy only just passed. Parquet also stays a file format, with no indexes, versioning or column-append semantics, which Lance provides at the table layer.",
    },
    vendorClaims: [
      "Variable-length list embeddings cost 'about 3x' a flat layout. This figure is from a secondary blog, not a Parquet project benchmark.",
    ],
    uncertain: [
      "Whether the FILE logical type has been merged into parquet-format. Databricks cites a commit; secondary sources call it contested.",
    ],
    sourceIds: ["merced-parquet-2026", "parquet-fsst-review", "databricks-file-type", "dremio-open-lakehouse-sep26"],
  },
  {
    id: "vortex", asOf: "2026-09",
    company: "Created by Spiral (SpiralDB) and contributed to LF AI & Data as an incubation project in August 2025, with Microsoft, Snowflake and Palantir named as supporters. Spiral raised $22M from Amplify Partners and General Catalyst, announced September 2025. Co-founder: Will Manning.",
    howItWorks: "An extensible columnar format and library in Rust that interoperates with Arrow without copying. It picks cascading encodings per type (ALP for floats, FSST for strings, FastLanes and others) and has pluggable layouts. It can evaluate filters on compressed data without decompressing it. File-format changes are managed through dated 'editions'.",
    status: "The library is at 0.86 (September 2026) with no 1.0 yet; the file format has been backward compatible since 0.36. DuckDB ships it as a core extension (January 2026), with DataFusion, Spark and Polars integrations and CUDA decompression kernels. The Iceberg integration PRs, in Java and Rust, are not merged. Milvus 3.0 uses Vortex as its default storage format, and Paimon lists it as a supported file format.",
    strengths: [
      "Strong scan and filter performance, with compute on compressed data.",
      "Vendor-neutral Linux Foundation governance with large supporters.",
      "A DuckDB core extension and a growing engine list.",
      "An active path into Iceberg and Milvus.",
      "A GPU roadmap.",
    ],
    weaknesses: [
      "A file format only: no table format, versioning or vector indexes.",
      "The library is pre-1.0, with frequent breaking API releases.",
      "Its Iceberg integration isn't merged.",
      "Blobs and growing columns depend on whatever table format hosts it.",
    ],
    whereItWins: "As a faster drop-in for Parquet under analytics engines, especially for DuckDB and DataFusion users, and inside Iceberg once that lands.",
    whereLanceWins: "A complete stack: file format, a versioned table format with cheap column addition, vector, full-text and scalar indexes, a Namespace spec for catalogs, and LanceDB as the query layer. Lance also has more catalog and table-format adoption today: Hudi, Paimon, Polaris, Gravitino, Unity Catalog.",
    fourNeeds: { scans: "strong", random: "strong", blobs: "weak", columns: "weak" },
    objection: {
      q: "Vortex claims 100 to 200 times faster random access than Parquet, like Lance. Why not Vortex?",
      a: "Both numbers are vendor benchmarks against Parquet, not against each other. The real difference is scope. Vortex is a file format that needs a table format, and its Iceberg path isn't merged. Lance ships the table layer, indexes and catalog integrations that retrieval and training need.",
    },
    vendorClaims: [
      "10 to 20 times faster scans, 5 to 10 times faster writes and 100 to 200 times faster random access than Parquet, at similar compression (Spiral and the Vortex project).",
      "18% faster than Parquet v2 on TPC-H SF100 in DuckDB (DuckDB blog).",
    ],
    sourceIds: ["lf-vortex", "spiral-announce", "vortex-site", "duckdb-vortex", "iceberg-vortex-pr", "milvus-3", "paimon-formats"],
  },
  {
    id: "nimble", asOf: "2026-09",
    company: "Meta, published under facebookincubator and open-sourced from Meta's internal format. About 735 GitHub stars.",
    howItWorks: "A columnar format for very wide tables with thousands of columns, used for ML feature engineering and training. It uses FlatBuffers metadata, block-based encoding and extensible encodings designed for SIMD and GPU decoding. It is tied to the Velox C++ engine, and Meta treats the library as the spec and discourages independent implementations.",
    status: "The README still calls it a work in progress with no stability or versioning guarantees. It is proven at Meta scale, but its community is early and centered on Velox.",
    strengths: [
      "Proven on Meta's widest ML training tables.",
      "Cheap metadata for thousands of columns.",
      "Designed for SIMD and GPU decoding.",
    ],
    weaknesses: [
      "No stability or versioning guarantees.",
      "One reference implementation, with others discouraged.",
      "A file format only: no table layer, versioning or indexes.",
      "Small ecosystem outside Meta.",
    ],
    whereItWins: "Velox or Presto stacks with extremely wide feature tables, mainly in Meta-like environments.",
    whereLanceWins: "A stable, multi-language, specified format with a table layer, indexes, blob support and broad engine and catalog integrations.",
    fourNeeds: { scans: "strong", random: "partial", blobs: "weak", columns: "weak" },
    objection: {
      q: "Meta built Nimble for ML training tables. Isn't that the same market?",
      a: "It overlaps on wide ML tables. But Nimble itself says it has no stability guarantees and discourages other implementations, which makes it a Velox component. Lance is built for an open, multi-engine lakehouse with retrieval as well as training.",
    },
    sourceIds: ["nimble-gh", "merced-formats"],
  },
  {
    id: "catalogs", asOf: "2026-09",
    company: "Apache Polaris came from Snowflake and Dremio and became a top-level project in February 2026. Unity Catalog is Databricks', with an open-source version in LF AI & Data. Apache Gravitino is backed commercially by Datastrato.",
    howItWorks: "Polaris implements the Iceberg REST catalog, with a Generic Table API for other formats. Unity Catalog governs tables, volumes, functions and models, with an Iceberg REST endpoint and new Delta APIs. Gravitino federates metadata across many sources, and since 1.1 it can act as a Lance Namespace server directly.",
    status: "All three can see Lance tables today, to different depths. Polaris registers Lance tables as generic tables with format 'lance' through the Lance Namespace; a January 2026 Polaris post names Spark, Ray, LanceDB, Trino, Flink and DuckDB. Credential vending, OAuth refresh and the commit path are still to come. Unity Catalog maps Lance tables as external tables; it doesn't know Lance natively. Gravitino has a built-in Lance REST service that can list, create, register and drop, but can't alter tables or manage indexes.",
    strengths: [
      "They are where platform teams already govern tables, so appearing in them is how Lance gets adopted.",
      "Polaris is vendor-neutral, Unity has the Databricks install base, and Gravitino has the deepest Lance support.",
    ],
    weaknesses: [
      "All three are Iceberg- or Delta-first. Lance support lacks credential vending and commit governance.",
      "None of them understands vector indexes.",
    ],
    whereItWins: "Not an either-or. The question is which catalog a customer runs.",
    whereLanceWins: "Not a format competitor. Each integration is a place Lance tables become visible to the platform team.",
    partnerOrRival: "Partners. The risk is only that a catalog's owner makes other formats feel first-class and Lance feel bolted on.",
    objection: {
      q: "Which catalogs support Lance natively?",
      a: "Gravitino ships a Lance REST namespace service. Polaris supports Lance through generic tables and the Namespace spec. Unity Catalog works through an external-table mapping. The known gaps, credential vending and the commit path, are on the Polaris roadmap.",
    },
    sourceIds: ["polaris-lance", "polaris-tlp", "uc-lance-spec", "gravitino-lance", "databricks-uc-dais26"],
  },
  {
    id: "ducklake", asOf: "2026-09",
    company: "Built by DuckDB Labs, with a hosted service from MotherDuck.",
    howItWorks: "Table metadata lives in a SQL database (DuckDB, PostgreSQL or SQLite) instead of files on object storage. Data files are Parquet, with Puffin files for deletion vectors. Small writes can be stored directly in the catalog database.",
    status: "v1.0 shipped on April 13, 2026 with a stable spec, data inlining, sorted tables, bucket partitioning, GEOMETRY and VARIANT. It has DuckDB, DataFusion, Spark, Trino and pandas clients. v2.0 plans branching, roles and incremental materialized views. No Lance or vector features were found.",
    strengths: [
      "Simple, fast metadata operations through SQL.",
      "Good for frequent small writes.",
      "Data files compatible with Iceberg's bucket transform and deletion vector format.",
    ],
    weaknesses: [
      "Parquet only.",
      "No vector, index or blob story.",
      "A young multi-engine ecosystem.",
    ],
    whereItWins: "DuckDB- or MotherDuck-centric analytics and small to medium lakehouses that want a SQL catalog's simplicity.",
    whereLanceWins: "Random access, vector and full-text search, blobs, and training and serving.",
    fourNeeds: { scans: "strong", random: "weak", blobs: "weak", columns: "partial" },
    objection: {
      q: "Does DuckLake's SQL catalog threaten file-based metadata like Lance's?",
      a: "It targets the metadata overhead of analytics, not AI access patterns. And DuckDB reaches Lance too, through its Lance extension and through catalogs like Polaris.",
    },
    sourceIds: ["ducklake-1-0"],
  },
  {
    id: "paimon", asOf: "2026-09",
    company: "An Apache project from the Flink community. Alibaba is prominent in it, and Kuaishou (Kwai) runs it in production.",
    howItWorks: "An LSM-based streaming table format with primary-key and append tables. 'Data evolution' with row tracking lets it update or add columns without rewriting existing files. BLOB values go into dedicated .blob files, which requires turning on row tracking and data evolution. A global index adds BTree and vector indexes, with IVF, PQ and DiskANN in a Rust library. Data files can be Parquet (the default), ORC, Avro, Lance, Vortex and more, and the docs recommend Lance for ML.",
    status: "1.4 is the stable docs version, and 2.0 is in planning. Apache Doris describes Paimon 2.0 capabilities (BLOB, VECTOR, VARIANT, data evolution, global row IDs and global index) in a September 2026 post. Doris 4.2, due at the end of September 2026, adds multimodal lakehouse queries over Paimon, Iceberg and Lance.",
    strengths: [
      "The table format closest to Lance's AI story: column evolution, blob files, a vector index, and Lance as a file format.",
      "Strong Flink streaming and CDC.",
      "Backing from Alibaba, Kuaishou and the Doris community.",
    ],
    weaknesses: [
      "The multimodal features are opt-in modes and newer.",
      "Vector index maturity is early in public sources.",
      "A smaller Western ecosystem.",
      "2.0 isn't confirmed as released.",
    ],
    whereItWins: "Flink-centric streaming lakehouses, especially on Alibaba Cloud or with Doris or StarRocks, that want streaming upserts and multimodal data in one table.",
    whereLanceWins: "Column evolution, blobs and vector indexes are native to Lance rather than opt-in modes on Parquet, and Lance has a broader Python, Ray and PyTorch ecosystem and Western catalog integrations.",
    fourNeeds: { scans: "strong", random: "partial", blobs: "partial", columns: "strong" },
    objection: {
      q: "Paimon has blobs, vector indexes and column evolution now. Isn't it Lance plus streaming?",
      a: "It's converging on Lance's feature list, and it recommends Lance files for ML. The difference is that these are native defaults in Lance with a wider AI engine ecosystem, and newer opt-in modes in a Flink-first format.",
    },
    vendorClaims: [
      "Kuaishou's test on 16M and 128M 2,048-dimension vectors: 96.0% to 99.6% recall, at 1.07 to 4.18 times the latency of Doris internal tables (Doris project blog).",
    ],
    uncertain: ["Whether Paimon 2.0 has been released, or only planned."],
    sourceIds: ["paimon-formats", "paimon-blob", "doris-paimon-2"],
  },
];
