export const layers = [
  { id: "compute", name: "Compute engines",
    analytics: "Spark, Trino, Snowflake, Databricks SQL, ClickHouse",
    lance: "DuckDB, Ray, Spark, PyTorch loaders, LanceDB",
    note: "This is where OLAP lives. Lance does not try to be a query engine. It lets engines read it. The DuckDB Lance extension gives you SQL over Lance tables, Ray and Spark run the distributed jobs, and data loaders stream training batches straight from the table.",
    say: "Lance competes for the data, not the compute. Every engine that reads Lance makes the format stronger, the same playbook that made Parquet and Iceberg win." },
  { id: "catalog", name: "Catalog",
    analytics: "Unity, Polaris, Glue, Nessie, Gravitino",
    lance: "Lance Namespace spec",
    note: "The Namespace spec names tables and groups them into a hierarchy so engines can find them without hard-coded paths. LanceDB OSS uses the simplest version, one directory of tables. The same spec lets Lance tables show up inside the catalogs a data platform team already runs.",
    say: "Your catalog can see Lance tables next to your Iceberg tables. Nobody has to pick a side on day one." },
  { id: "table", name: "Table format",
    analytics: "Iceberg, Delta, Hudi",
    lance: "Lance tables: manifests, fragments, versioned indexes",
    note: "Each commit writes a new immutable manifest, so time travel is built in. Fragments are lists in the manifest, not files, so adding a column means adding new data files to each fragment. Vector, full-text and scalar indexes are immutable files the manifest points to, so they always match the snapshot you query.",
    say: "Iceberg versions your data. Lance versions your data and your indexes together, which is what retrieval and training need." },
  { id: "file", name: "File format",
    analytics: "Parquet: row groups and a footer",
    lance: "Lance files: pages, no row groups, adaptive encodings",
    note: "Parquet groups rows into row groups. Too small and you get runt pages that read badly from object storage. Too large and writers buffer huge amounts of memory. Lance drops row groups, streams roughly 8 MB pages per column, and picks an encoding per column: random-access friendly for wide values like embeddings, scan friendly for narrow ones.",
    say: "You don't have to decide at write time whether this table is for scans or lookups. That decision is what hurts AI pipelines on Parquet." },
  { id: "storage", name: "Object storage",
    analytics: "S3, GCS, ADLS",
    lance: "S3, GCS, ADLS, local disk",
    note: "Same bucket, same security model, same bill. Lance tables can sit next to Iceberg tables. This is the heart of the coexistence story: nothing about adopting Lance forces a migration off the lakehouse you already have.",
    say: "Lance lives in the bucket you already pay for. The question is which format each workload reads." },
]
