export const market = [
  { id: "wh", label: "Snowflake, BigQuery", x: 0.12, y: 0.12, note: "Warehouses own structured analytics and BI. LanceDB does not fight them on dashboards. The pitch: video, images and embeddings do not belong in a warehouse, and exporting them to another system breaks lineage." },
  { id: "lh", label: "Databricks, Iceberg", x: 0.3, y: 0.28, note: "The real conversation. Iceberg won the analytics table format war once Snowflake and Databricks went all in. LanceDB's public stance is coexistence: Iceberg for analytics interop, Lance for AI workloads. Crunchbase lists Databricks Ventures as a LanceDB investor." },
  { id: "olap", label: "ClickHouse, Druid, Pinot", x: 0.2, y: 0.06, note: "Real-time OLAP engines with their own storage. Fast aggregations over narrow structured columns. Not a target. If the workload is pure aggregation over structured rows, you don't need Lance." },
  { id: "duck", label: "DuckDB", x: 0.38, y: 0.18, note: "A partner, not a competitor. The DuckDB Lance extension gives SQL and retrieval over Lance tables. This is how Lance answers 'but can I query it.' DuckDB also ships a Vortex extension, so it partners with every new format." },
  { id: "s3v", label: "S3 Vectors", x: 0.72, y: 0.3, note: "AWS's native vector storage in S3. GA December 2025, up to 2 billion vectors per index, and AWS claims up to 90% lower cost than dedicated vector databases. Stores vectors and metadata, not the images, features or training sets." },
  { id: "tpuf", label: "turbopuffer", x: 0.8, y: 0.2, note: "Vector and full-text search built directly on object storage, a design close to LanceDB's own retrieval layer. A strong retrieval competitor, but not a lakehouse for training data." },
  { id: "vdb", label: "Pinecone, Qdrant, Milvus", x: 0.88, y: 0.42, note: "Where LanceDB started and what it is climbing out of. Vector databases do fast random access on embeddings, but the raw data, features and training sets live somewhere else. Lance keeps vectors next to the source data." },
  { id: "vast", label: "VAST Data", x: 0.62, y: 0.76, note: "Tracxn lists VAST among LanceDB's top competitors. VAST sells storage plus a database layer as one system for AI. The contrast: Lance is an open format you can run in any bucket and any cloud, VAST is a platform you buy." },
  { id: "lance", label: "LanceDB", x: 0.86, y: 0.88, self: true, note: "Multimodal data plus mixed access. One versioned table serves curation, feature engineering, retrieval and training, with scans and random access on the same bytes." },
]
