export const sources = [
  { id: "dq-lance", title: "How Lance enables the Multimodal Lakehouse", publisher: "The Data Quarry (Prashanth Rao)", url: "https://thedataquarry.com/blog/how-lance-enables-the-multimodal-lakehouse/", date: "2026-03-27" },
  { id: "lance-paper", title: "Lance: Efficient Random Access in Columnar Storage through Adaptive Structural Encodings", publisher: "arXiv", url: "https://arxiv.org/abs/2504.15247", date: "2025-04" },
  { id: "lancedb-docs", title: "LanceDB documentation", publisher: "LanceDB", url: "https://docs.lancedb.com/" },
  { id: "lancedb-home", title: "LanceDB: Multimodal Lakehouse for AI", publisher: "LanceDB", url: "https://www.lancedb.com/" },
  { id: "lancedb-series-a", title: "LanceDB Raises $30M Series A to Build the Multimodal Lakehouse", publisher: "LanceDB", url: "https://www.lancedb.com/blog/series-a-funding", date: "2025-06-24" },
  { id: "lancedb-newsletters", title: "LanceDB newsletter archive (Aug and Sep 2026 issues)", publisher: "LanceDB", url: "https://www.lancedb.com/category/newsletter" },
  { id: "lancedb-announcements", title: "LanceDB announcements (SDK 1.0, governance, Hugging Face, DuckDB)", publisher: "LanceDB", url: "https://www.lancedb.com/category/announcement" },
  { id: "lancedb-iceberg", title: "The Future of Open Source Table Formats: Apache Iceberg and Lance", publisher: "LanceDB", url: "https://www.lancedb.com/blog/the-future-of-open-source-table-formats-iceberg-and-lance", date: "2025-04-08" },
  { id: "lancedb-mmlh-pdf", title: "The Multimodal Lakehouse (whitepaper)", publisher: "LanceDB", url: "https://learn.lancedb.com/hubfs/lancedb-multimodal-lakehouse.pdf" },
  { id: "tc-seed", title: "LanceDB, which counts Midjourney as a customer, is building databases for multimodal AI", publisher: "TechCrunch", url: "https://techcrunch.com/2024/05/15/lancedb-which-counts-midjourney-as-a-customer-is-building-databases-for-multimodal-ai/", date: "2024-05-15" },
  { id: "yc-lancedb", title: "LanceDB company page", publisher: "Y Combinator", url: "https://www.ycombinator.com/companies/lancedb" },
  { id: "tracxn", title: "LanceDB company profile", publisher: "Tracxn", url: "https://tracxn.com/d/companies/lancedb/__ie1HuEEUoPOIc3tEX5yowY9yMJz9kdNTH01mwCePxLw", date: "2026-07-20" },
  { id: "crunchbase", title: "LanceDB company profile", publisher: "Crunchbase", url: "https://www.crunchbase.com/organization/lancedb" },
  { id: "register-lance", title: "Lance takes aim at Parquet in file format joust", publisher: "The Register", url: "https://www.theregister.com/2025/10/14/lance_parquet/", date: "2025-10-14" },
  { id: "db-tabular", title: "Databricks agrees to acquire Tabular", publisher: "Databricks", url: "https://www.databricks.com/company/newsroom/press-releases/databricks-agrees-acquire-tabular-company-founded-original-creators", date: "2024-06-04" },
  { id: "tt-tabular", title: "Databricks $1B-plus Tabular acquisition adds Iceberg support", publisher: "TechTarget", url: "https://www.techtarget.com/searchdatamanagement/news/366588032/Databricks-1B-plus-Tabular-acquisition-adds-Iceberg-support", date: "2024-06-06" },
  { id: "bf-tabular", title: "Databricks buys Tabular to win the Iceberg war", publisher: "Blocks and Files", url: "https://blocksandfiles.com/2024/06/05/databricks-buys-tabular-to-win-the-iceberg-war/", date: "2024-06-05" },
  { id: "atlan-v3", title: "Apache Iceberg v3: New Features and Snowflake 2026 Guide", publisher: "Atlan", url: "https://atlan.com/know/snowflake/apache-iceberg-v3/", date: "2026-06-03" },
  { id: "ryft-v3", title: "Apache Iceberg V3: Is It Ready?", publisher: "Ryft", url: "https://www.ryft.io/blog/apache-iceberg-v3-is-it-ready", date: "2025-12-16" },
  { id: "db-v3", title: "Apache Iceberg v3: Moving the Ecosystem Towards Unification", publisher: "Databricks", url: "https://www.databricks.com/blog/apache-icebergtm-v3-moving-ecosystem-towards-unification", date: "2025-06-02" },
  { id: "iceberg-intro-2026", title: "A 2026 introduction to Apache Iceberg", publisher: "Alex Merced (dev.to)", url: "https://dev.to/alexmercedcoder/a-2026-introduction-to-apache-iceberg-4nd8" },
  { id: "lf-vortex", title: "LF AI & Data Foundation Hosts Vortex Project", publisher: "Linux Foundation", url: "https://www.linuxfoundation.org/press/lf-ai-data-foundation-hosts-vortex-project-to-power-high-performance-data-access-for-ai-and-analytics", date: "2025-08-07" },
  { id: "vortex-gh", title: "vortex-data/vortex", publisher: "GitHub", url: "https://github.com/vortex-data/vortex" },
  { id: "duckdb-vortex", title: "Announcing Vortex Support in DuckDB", publisher: "DuckDB", url: "https://duckdb.org/2026/01/23/duckdb-vortex-extension", date: "2026-01-23" },
  { id: "aws-s3v-ga", title: "Amazon S3 Vectors is now generally available with 40 times the scale of preview", publisher: "AWS", url: "https://aws.amazon.com/about-aws/whats-new/2025/12/amazon-s3-vectors-generally-available/", date: "2025-12-02" },
  { id: "aws-s3v-regions", title: "Amazon S3 Vectors expands to 17 additional AWS Regions", publisher: "AWS", url: "https://aws.amazon.com/about-aws/whats-new/2026/03/s3-vectors-expands-17-regions", date: "2026-03" },
  { id: "datalake-2026", title: "Data lake platform notes (Polaris, DuckLake, S3 Tables, Gravitino)", publisher: "Smithery skill notes", url: "https://smithery.ai/skills/vasilyu1983/data-lake-platform" },
  { id: "merced-lance-iceberg", title: "Lance and Iceberg for Multimodal AI Data", publisher: "Alex Merced", url: "https://iceberglakehouse.com/posts/2026-05-24-lance-iceberg-multimodal/", date: "2026-05-24" },
  { id: "lancescope", title: "LanceScope", publisher: "Michael Lynn", url: "https://lancescope.mlynn.dev" },
]
